/** English interface strings, typed against the Chinese dictionary: every key
 *  in core.zh.ts must appear here with the same shape. British spelling. */
import { zh } from "./core.zh";

export const en: typeof zh = {
  // brand / shell
  appName: "CrystalPilot",
  legacyUi: "Legacy interface",
  localUser: "Local workbench",
  settings: "Settings",
  appearance: "Appearance",
  themeSystem: "System",
  themeLight: "Light",
  themeDark: "Dark",
  fontSize: "Font size",
  fontSizeNames: { 13: "Small", 14: "Standard", 15: "Large", 16: "Extra large" } as Record<
    number,
    string
  >,
  sidebarStatusNodes: "nodes",
  sidebarStatusAlertsA: "level A",
  sidebarStatusNoWork: "No refinement nodes yet",

  // sidebar
  newThread: "New conversation",
  projects: "Projects",
  recentProjects: "Recent projects",
  moreProjects: "More",
  moreProjectsTip: "Auto-generated test projects (ui-import-…) and projects you have hidden",
  hideProject: "Hide",
  hideProjectTip: "Move from the recent list to “More” (this browser only)",
  unhideProject: "Restore",
  renameProject: "Rename",
  renameProjectTip:
    "Give the project a display name, stored in its settings; the sidebar, the status board and the open dialog all follow. Leave it empty to restore the folder name",
  renamePlaceholder: "Display name; Enter saves, Esc cancels",
  openProject: "Open project",
  noThreads: "No conversations yet",
  running: "Running",

  // project status board
  statusBoard: "Project status",
  statusOpen: "Open",
  statusIdle: "Idle",
  statusNoWork: "Not started",
  statusNodes: "Nodes",
  statusDeliveries: "Deliveries",
  statusBestR1: "Best R1",
  statusAlertsA: "Level A alerts",
  statusRefresh: "Refresh",

  // open-project dialog
  openProjectTitle: "Open project",
  openProjectMode: "Open as",
  openFolderMode: "Project folder",
  openCifMode: "CIF only (view)",
  openProjectHint: "Enter a project path on the machine that runs the workbench; put new projects outside the program folder.",
  pathPlaceholder: "H:\\CrystalPilot-projects\\sample",
  cifChooseFile: "Choose a CIF file",
  cifDestination: "Save into a new structure project",
  cifDestinationHint: "H:\\CrystalPilot-projects\\sample-view",
  cifImport: "Import and view",
  cifImportHint:
    "No HKL needed: view the structure, take measurements and analyse the packing. The original file is not modified; without diffraction data no refinement metrics, difference density or residual electron counts are computed.",
  cifBlockLabel: "Multi-structure file: data block (optional)",
  cifBlockHint: "Usually left empty; with several structures, give the name after data_",
  structureOnlyTitle: "Structure-only analysis",
  structureOnlyNote: "No reflection data · literature metrics are not results of this refinement",
  structureNeedsReflections:
    "No observed reflection data: density maps and residual peaks are unavailable; geometric pores can still be viewed.",
  structureReportedMetrics: "Metrics reported by the source CIF (not re-refined)",
  electronsNotComputed: "Electron count not computed",
  analysisKeepStructure: "Keep the structure view during analysis",
  analysisStageNames: {
    interactions: "Interactions",
    topology: "Topology and shape",
    guests: "Guest sites",
    pores: "Pores and packing",
  },
  analysisStageStates: {
    waiting: "Waiting",
    running: "Computing",
    ready: "Ready",
    error: "Failed",
    unsupported: "Not supported by this data",
    cancelled: "Not continued",
  },
  analysisWorking: "Finished items are shown first; the rest are still computing",
  analysisFinished: "This analysis round has finished",
  analysisCached: "Existing analysis results loaded",
  analysisStop: "Stop the remaining computations",
  analysisPaused: "This window has stopped waiting",
  analysisPauseNote: "Finished results are kept; a shared job used by other windows may continue.",
  analysisCancelNote: "The running engine computation cannot be interrupted at once; no further item starts after it returns.",
  analysisErrorDetails: "Show the reason",
  open: "Open",
  opening: "Opening…",
  cancel: "Cancel",

  // welcome / project home
  heroTitle: "What shall we do with this crystal?",
  heroSubtitle: "Open a project folder and hand the diffraction data to CrystalPilot.",
  projectHeroSubtitle: "Describe your crystal and your goal to start an autonomous refinement conversation.",

  // composer
  composerPlaceholder: "Type freely (paste or drop images and files)",
  send: "Send",
  stop: "Stop",
  steer: "Steer",
  attach: "Add attachment",
  uploading: "Uploading…",
  attachedPrefix: "Attachment",
  attachRemove: "Remove attachment",
  attachRetry: "Retry upload",
  attachTooMany: "At most 8 attachments per message",
  attachTooLarge: "Over the 50 MB limit",
  attachUploadFailed: "Upload failed",
  attachWaitUploading: "Attachments are still uploading, please wait…",
  dropToAttach: "Release to add the files as attachments",
  attachImageHint: "Images go to the model with the message; text is extracted from PDF and Word files automatically",
  resizeHandle: "Drag to resize the column (double-click to reset)",

  // permission modes
  permReadonly: "Read-only",
  permCopilot: "Ask for approval",
  permAuto: "Automatic",
  permFull: "Full access",
  permReadonlyDesc: "Only reads the project; makes no changes",
  permCopilotDesc: "Asks me before changing the model, writing files or running commands",
  permAutoDesc: "Runs inside the workspace on its own; asks when a step crosses a line (credentials, the data drive, kill, push)",
  permFullDesc: "May access the files on your computer without restriction",
  permTitle: "How should CrystalPilot's actions be approved?",
  permChangeBusyError: "The permission mode cannot be changed while a turn is running",

  // chat items
  reasoningSummary: "Reasoning summary",
  technicalDetails: "Technical details",
  rawCommand: "Raw command",
  toolRunning: "Running",
  toolDone: "Done",
  toolFailed: "Failed",
  toolInterrupted: "Not completed",
  toolNoResult: "No result received",
  // project storage (project home)
  storageTitle: "Project storage",
  storageUser: "User data",
  storageResults: "Deliverables",
  storageSystem: "Generated by the system",
  storageReclaimable: "Reclaimable",
  storagePreview: "Show what can be cleaned",
  storageNothing: "Nothing to clean",
  storageApply: "Clean up",
  storageFreed: "Freed",
  storageSkipped: "items skipped",
  storageBusy: "A turn is running; clean up after it finishes",
  storagePlanHint: "List first, then apply: only intermediate products that no node or delivery references are touched. User files, the node store, reflection-data versions and CrystalPilot Results are never modified.",
  storagePlanList: "Itemised list",
  storageKindLink: "Replace with a hard link (content unchanged)",
  storageKindStrip: "Replace reflections embedded in CIFs with a reference (restored on delivery)",
  storageKindDelete: "Delete intermediate files",
  storageKindRmdir: "Delete finished staging directories",
  storageRules: "Retention rules: jobs referenced by the node tree or a delivery are kept whole; unreferenced jobs keep .ins/.res/.lst and only the structure-factor tables are reclaimed; reflection data is stored once (as data versions) and job directories reference it through hard links.",
  toolNoResultHint:
    "This step started, but its completion event did not arrive before the turn ended; the system counts it neither as a success nor as a failure. The raw events received are shown below.",
  toolInterruptedHint: "The turn was stopped or failed while this step was running; its result never arrived.",
  rawEvents: "Raw events",
  imageView: "View image",
  railQuestion: "Waiting for an answer",
  command: "Command",
  exitCode: "Exit code",
  output: "Output",
  fileChange: "File change",
  digestPrefix: "Ran ",
  digestCommands: "commands",
  digestObserves: "inspections",
  digestOthers: "actions",
  workedFor: "Worked for",
  workThinking: "Thinking",
  // peak numbering (the P3 same-source check of the peak table)
  peakOrdinalNote:
    "The numbers are the viewer's internal ordinals; describe a peak to the agent by position and height (the quote button already does)",
  // global display density switch (P1-6)
  viewConcise: "Concise",
  viewVerbose: "Detailed",
  viewModeTitle: "Display density: concise shows conclusions only; detailed expands every command and output",
  // sticky current-action row (P1-5)
  stickyThinking: "Thinking…",
  stickyApproval: "Waiting for approval…",
  stickyEditingFile: "Editing a file…",
  stickySearching: "Searching the web…",
  // turn failures in plain words (P1-9)
  turnErrTimeout: "The upstream response timed out; retry in a moment. Completed nodes are not affected",
  turnErrRateLimit: "Upstream rate limit (429); wait a moment and resend the message",
  turnErrUpstream: "Upstream service error",
  showEarlierPrefix: "Show the earlier ",
  showEarlierSuffix: " items",
  showEarlierServer: "Load earlier records",
  showEarlierLoading: "Loading…",
  showEarlierRemainingPrefix: "",
  earlierInputs: "Earlier inputs (see “Show earlier” for the related steps)",
  jumpToLatest: "Back to latest",
  railIdle: "Idle",
  railLastTurn: "Last turn",
  railNode: "Node",
  railSteerable: "Steerable",
  railFresh: "Not started yet",
  railApproval: "Waiting for your approval",
  railFailed: "Last turn failed",
  railInterrupted: "Last turn interrupted",
  deliveryStatusFinal: "Final",
  deliveryStatusProvisional: "Provisional",
  deliveryStatusDiagnostic: "Diagnostic",
  deliveryNode: "Node",
  deliveryAllFiles: "All",
  deliveryFilesUnit: "files",
  deliveryOpenArtifacts: "Artifacts tab",
  // round-3 WP1 status envelope (summary.tool_status)
  envNoChange: "No change",
  envInconclusive: "Inconclusive",
  envAgainst: "Evidence against",
  envTimeout: "Timed out · partial result",
  envCancelled: "Cancelled",
  showEarlierRemainingSuffix: " more",
  commandFullOutput: "Show full output",
  commandFullOutputChars: "characters",
  commandFullOutputMissing: "The server has no full output for this command",
  errorAreaTitle: "This area ran into an error",
  errorAreaHint: "Other areas are unaffected; the diagnostic has been recorded.",
  errorAreaRetry: "Reload this area",
  errorAreaCopy: "Copy diagnostic",
  errorAreaCopied: "Copied",
  asuFlagTipPrefix: "ASU warning: ",
  asuFlagDetached: "detached fragment",
  asuFlagGhosts: "suspected ghost atoms",
  asuFlagTipSuffix:
    "; an error in a reviewer's eyes. Resolve it with assemble_asu or the ghost adjudication procedure before delivery",
  webSearch: "Web search",
  todoList: "To-do list",
  errorItem: "Error",
  clientError: "Client error",

  // approvals
  approve: "Approve",
  reject: "Reject",
  approveForSession: "Always allow in this session",
  approvalPending: "Awaiting approval",
  approvalAccepted: "Approved",
  approvalRejected: "Rejected",
  approvalAuto: "Approved automatically",
  approvalTimeout: "Timed out",
  approvalResolved: "Handled in the background",
  approvalAutoSession: "Approved automatically (allowed for this session)",
  approvalInComposer: "Approve in the input area below",
  approvalQueuePrefix: "Pending approval",
  approvalShowParams: "Parameters",
  approvalRunCommand: "Run command: ",
  approvalMcpTool: "Call tool ",

  // MCP engine health
  mcpDownBanner: "The crystallography tool service is unreachable and the refinement tools are unavailable; restart the engine to recover",
  mcpRestart: "Restart engine",
  mcpRestarting: "Restarting the engine…",
  mcpRestartBusy: "A turn is running; restart after it finishes",
  sysMcpDown: "Crystallography tool service unreachable",
  sysMcpWaiting: "Starting the crystallography tool service…",
  sysMcpReady: "Crystallography tools ready",
  sysMcpFailed: "The crystallography tools failed to start",
  sysMcpToolsUnit: "tools",
  sysMcpTimeout: "The crystallography tools were not ready within the time limit; this turn may lack tools",
  sysEngineRestarted: "Engine restarted; the tool service is back",

  // attach menu / raw frames directory
  attachUpload: "Upload files (small files such as cif/hkl/res)",
  attachFramesDir: "Reference a raw-frame directory…",
  attachFramesDirDesc:
    "Hundreds of diffraction frames are not uploaded: enter a local directory path; after a check it is handed to import_frames, which reads it in place",
  framesDirPlaceholder: "e.g. D:\\data\\scan1 or H:\\...\\cbf",
  framesProbe: "Check",
  framesFound: "diffraction frames",
  framesNone: "No diffraction frames of a known format found",
  framesInsert: "Insert into the input box",

  // turn status
  turnStarted: "Turn started",
  turnCompleted: "Turn completed",
  turnDone: "Done",
  turnInterrupted: "Interrupted",
  turnFailed: "Failed",
  working: "Working…",

  // channel status
  connecting: "Connecting…",
  reconnecting: "Reconnecting…",
  recovering: "Reconnecting to the project…",
  channelDead: "Connection lost; retrying automatically",

  // right pane
  rightPaneTitle: "Crystal pane",
  rightPaneComing: "Crystal pane coming soon",
  rightPaneComingDesc: "The structure view, node tree and metrics arrive in the next stage.",
  tabStructure: "Structure",
  tabNodes: "Node tree",
  tabMetrics: "Metrics",
  tabArtifacts: "Artifacts",
  tabValidation: "Validation",
  tabAnalysis: "Analysis",
  // analysis tab (R3.5)
  anScope: "Symmetry-unique table · whole crystal · independent of the displayed extent",
  anInteractions: "Interactions",
  anPores: "Pores",
  anGuests: "Guest sites",
  anLoading: "Computing the analysis tables…",
  anError: "The analysis tables could not be built",
  anRetry: "Retry",
  anNoNode: "No node yet",
  anNone: "None",
  anNoInteractions: "No interactions found under the current criteria",
  anNoVoids: "This structure has no solvent-accessible voids",
  anPassing: "Meets the criteria",
  anIntra: "Intramolecular",
  anInter: "Intermolecular",
  anPassingOf: (passing: number, total: number) => `${passing} of ${total} meet the criteria`,
  anQuote: "Quote",
  anMore: "Show all",
  anLess: "Collapse",
  anTruncated: "Truncated; only the most recent are kept",
  anMissingRings: "Missing rings",
  anMissingRingsTail:
    "rings that close through a symmetry element cannot be represented by the ring finder; the π–π and C–H···π rows that involve them are not in the table",
  anRcsrComponents: "components",
  anSystreError: "Systre error",
  anPending: "Not implemented",
  anDim: ["Isolated cavity", "1-D channel", "2-D layer", "3-D network"],
  anLcd: "LCD",
  anPld: "PLD",
  anSite: {
    cage_cavity: "Inside a cage",
    channel: "Channel",
    cavity: "Intermolecular cavity",
    interstitial: "Lattice interstice",
  } as Record<string, string>,
  anSiteCage: "Inside a cage",
  anHost: "Host",
  anGuestCopies: "copies",
  anClearance: "Nearest clearance",
  anToCentre: "To the inscribed-sphere centre",
  anCriteria: "Criteria",
  anNoGuests: "The model has no guest or counter-ion fragments",
  anGuestsFailed: "Guest assignment could not be computed",
  sidebarOpen: "Open sidebar",
  // completed-turn fold (R6)
  turnFoldPrefix: "Steps",
  foldTools: "tool calls",
  foldThinks: "reasoning blocks",
  foldCommands: "commands",
  foldApprovals: "approvals",
  foldSubagents: "sub-agent calls",
  // delivery summary card (R6)
  deliveryTitle: "Delivery summary",
  deliveryFromTools: "The file list is read from the artifacts directory (tool results), not from the conversation text",
  deliveryNoFiles: "The artifacts directory has no files yet (or has not been refreshed)",
  deliveryWaived: "Waived",
  // what final.cif IS, and whether a person can continue by hand
  deliveryCifGradeActa: "SHELXL ACTA CIF",
  deliveryCifGradeModel: "Model CIF",
  deliveryCifGradeModelTip:
    "Coordinates come from the node; the statistics come from that model's own measurement (a zero-cycle SHELXL run or the current metrics); no e.s.d.s and no geometry tables. For an ACTA CIF, run run_shelxl(mode='adopt', l_s≥1) on that node",
  deliveryHandoverReady: "Hand-over files complete (res / cif / ins / hkl / p4p)",
  deliveryHandoverMissing: "Hand-over files missing",
  // approval facets (R6)
  approvalWhat: "What",
  approvalWhy: "Why",
  approvalRisk: "Risk",
  approvalFiles: "Affects",
  riskObserve: "Read-only tool: changes no model and writes no file",
  riskMutate: "Changes the model: on success it is committed as a new node, and checkout rolls it back",
  riskDeliver: "Writes delivery files (CIF / reports) into the project directory",
  riskUpload: "Uploads the CIF and structure factors to the external checkcif.iucr.org",
  riskShell: "Runs a shell command (outside the sandbox, judged by the blocklist)",
  riskFile: "Modifies workspace files",
  riskUnknown: "Unrecognised action type; check the parameters",
  // quote anchors (R6) + composer chips / transcript jumps (round-3 R6)
  anchorChip: "Anchor",
  anchorRailLabel: "Quotes",
  anchorRemove: "Remove this quote",
  anchorJump: (node: string) => `Go back to ${node} to see this quote (historical value, no checkout)`,
  // steer receipts (round-3 R6)
  receiptSending: "Sending…",
  receiptPersisted: "Recorded",
  receiptSubmitted: "Delivered to the model",
  receiptFailed: "Not delivered to the model",
  receiptRetry: "Retry",
  // question cards (round-3 R6)
  askTitle: "Your decision is needed",
  askSettled: "Settled",
  askDispute: "Disagreement",
  askQuestion: "Question",
  askFallback: "If you do not know",
  askAnswerSelf: "Answer in my own words",
  askHint: "Your answer is handed to the agent as a prior, which it verifies against the data; if unsure, choose “don't know” and it takes the conservative path.",
  // stage track (R6)
  stageTrackTitle: "Stages",
  stageBasisSituation: "Stage determined by situation_report",
  stageBasisTool: "Stage inferred from the latest tool",
  stageNoTurns: "No completed turn in this stage yet",
  stageToolsUnit: "tool calls",
  // subagent directory (R6)
  subagentsTrigger: "Sub-agents",
  subagentsNone: "No sub-agent has been delegated to in this thread",
  subagentPrompt: "Task",
  subagentStatus: "Status",
  collabRow: "Sub-agent",
  // structure class (analysis tab)
  scTitle: "Structure class",
  scAuto: "Not declared (using the suggestion)",
  scClasses: {
    small_molecule: "Small molecule",
    macrocycle: "Macrocycle",
    cage: "Cage",
    framework: "Periodic framework (MOF / COF / HOF)",
    salt_cocrystal: "Salt / co-crystal",
  } as Record<string, string>,
  scSuggested: "Suggested",
  scBasis: "Basis",
  scAdopt: "Adopt",
  scTip:
    "Tell the system what this crystal is; the analysis tab then expands only the blocks relevant to it, and the others can still be opened with “Show all”. The class is also written into the project settings for the agent to read.",
  scHiddenPrefix: "Collapsed by class: ",
  scShowAll: "Show all",
  scShowByClass: "Show by class",
  scSaveFailed: "The class is remembered on this machine but could not be written to the project settings: ",
  sidebarClose: "Close sidebar",
  // topology (R4)
  anTopology: "Topology",
  anNets: "Independent nets",
  anNetsUnit: "nets",
  anNoNets: "No periodic net (molecular crystal)",
  anNoNetsShort: "No periodic net",
  anInterpenetrated: "Symmetry-related nets · interpenetration undetermined",
  anInterpenetratedYes: "Interpenetrated · ring-crossing test",
  anInterpenetratedNo: "Symmetry-related but not interpenetrated (no ring crossing found)",
  anInterlocked: "Symmetry-related 1-D chains (mechanical interlocking undetermined)",
  anInterlockedYes: "Mechanically interlocked 1-D chains (ring-crossing test)",
  anRelation: {
    translation: "Related by a lattice translation",
    space_group_op: "Related by a space-group operation",
    independent: "Crystallographically independent",
  } as Record<string, string>,
  anSimplifiedNet: "Simplified net",
  anNodes: "Nodes",
  anEdges: "Edges",
  anNodeKind: {
    metal_cluster: "Metal cluster",
    branch_linker: "Branching linker",
  } as Record<string, string>,
  anRod: "Rod (periodic cluster)",
  anHelices: "Helical chains",
  anNoHelices: "No helical chains",
  anHand: { right: "Right-handed", left: "Left-handed" } as Record<string, string>,
  anAchiral: "Achiral",
  anRacemic: "Racemic packing",
  anPitch: "Pitch",
  anFinite: "Finite fragments (molecules / cages / counter-ions)",
  anHostRole: "Host",
  anGuestRole: "Guest",
  anLargestCycle: "Largest chordless cycle",
  anNoRing: "No ring",
  anSphericity: "Sphericity",
  anAspect: "Aspect ratio",
  anLongest: "Longest axis",
  anDefinition: "Definitions and notes",
  anTopologyFailed: "The topology block could not be computed",
  ovNet: "Simplified net",
  ovNetTip:
    "Node-and-linker simplified net (R4): metal clusters contracted to nodes, linkers to edges carrying lattice translations. A description for a person to check, not a verdict; read from this node's analysis product",
  netLoading: "Fetching the simplified net…",
  netEmpty: "The simplified net is empty: no metal nodes, or every linker is terminal",
  anPacking: "Packing index",
  anPerAtom: "Å³ per non-H atom",
  anCentre: "Inscribed-sphere centre",
  anCentroid: "Centroid",
  anElectrons: "e",
  anPldAlong: "along a/b/c",
  anElectronsRecomputed: "Recomputed mask electrons",
  anElectronsSnapshot: "Refinement mask snapshot",
  anElectronsPerCell: "e/cell",
  anElectronsDisagree: "Same basis (whole cell) but they differ by more than 20 %: the refinement mask snapshot is authoritative for the count",
  anElectronsUnconverged: "The recomputation did not converge; the refinement mask snapshot is authoritative",
  anParamsNode: "Mask parameters come from this node's own solvent_mask",
  anParamsDefaults: "Mask parameters are a default preview (solvent_mask has not run on this node)",
  collapse: "Collapse",
  expand: "Expand",
  focusEnter: "Focus on the structure: the right pane takes at least 64 % of the window and the left column folds into a drawer; Esc or a second click restores the layout",
  focusExit: "Leave focus",

  // validation tab (checkCIF)
  ccEmptyTitle: "No checkCIF result yet",
  ccEmptyDesc: "Alerts appear here after run_checkcif",
  ccRunning: "Running checkCIF…",
  ccFailed: "The checkCIF run failed",
  ccPartialNote:
    "The alert details are incomplete, contain records that could not be parsed, or have inconsistent counts; unknown totals are given as lower bounds from the alerts recovered. Check the original report.",
  ccCountsUnknown: "Total unknown",
  ccViewReport: "View the explanations",
  ccViewAlerts: "Back to the alert list",
  ccNoKb: "No knowledge-base note for this alert yet",
  ccKbMeaning: "Meaning",
  ccKbCauses: "Common causes",
  ccKbRemedy: "Usual remedy",
  ccSourceLocal: "Local PLATON",
  ccSourceSameNode: "Report from the node being viewed",
  ccSourceDifferentNode: "This check belongs to another node; it does not mean the current model has been validated",
  ccSourceOlderDelivery: "The delivery has been updated since; this report does not check the new version",
  ccSourceUnknown: "The source version was not recorded or cannot be read right now; shown as a historical report",
  ccDeliveryVersion: "Delivery version",
  ccViewSourceNode: "View the source node",
  ccReportScope:
    "This shows the latest check report of this conversation; it is not recomputed when you switch to a historical node. Validate again after the model or the data changes.",
  ccQuoteAlertTip: "Put this alert's code and text into the input box and ask how to handle it",
  ccQuoteAllTip: "Put the list of level A and B alerts into the input box and ask which to handle first",
  ccSourceIucr: "IUCr official",
  ccLevelA: "A serious",
  ccLevelB: "B potentially serious",
  ccLevelC: "C check",
  ccLevelG: "G note",

  // coordination section (metrics tab)
  coordTitle: "Coordination environment",
  coordMetal: "Metal",
  coordCN: "CN",
  coordRange: "Bond-length range (Å)",
  coordLigands: "Ligands",
  coordNone: "No metal atoms in the current scene",
  coordHint: "Click a row to highlight the atom in the structure view",
  coordAsuCaveat:
    "Counted in the current scene (asymmetric unit); coordination bonds across symmetry are not included. Switch to “grow” to see the complete coordination sphere",

  // branch compare (nodes tab)
  branchCompareTitle: "Branch comparison",
  branchHead: "Head node",
  branchBest: "Lowest R1",
  branchViewing: "Viewing",

  // artifacts / usage
  artifacts: "Artifacts",
  tokens: "Tokens",
  contextWindow: "Context",
  tokensUsed: "Tokens used in this session",
  usageTitle: "Token usage",
  usageInput: "Input",
  usageCached: "Cached",
  usageOutput: "Output",
  contextUsedSuffix: "used",
  noUsage: "No usage data for this turn yet",

  // crystal pane - structure header card (Olex2 info-panel analog)
  headerVsParent: "Parent node",
  headerFormulaTip:
    "Composition of the asymmetric unit (Hill order, counted over the atoms of the identity operation); " +
    "it does not change with the extent or with growing, because it always counts the independent part",
  headerDmin: "Resolution",
  headerDminTip: "The highest resolution actually used in this refinement (including a SHEL cut-off)",
  headerRintTip:
    "Rint, the merging agreement: the internal consistency of the data itself, which sets a floor that " +
    "R1 cannot go below. Read it together with crystal quality and diffraction strength, not against a fixed line",
  headerCompleteness: "Completeness",
  headerUnique: "Unique reflections",
  headerUniqueTip: "Number of unique reflections (subtitle: redundancy = total observations / unique)",
  headerPeak: "Peak",
  headerHole: "Hole",
  headerParamsTip:
    "Number of refined parameters (subtitle: number of restraints; the second line is the data-to-parameter " +
    "ratio, and a low ratio means the model has more freedom than the data can support)",
  headerDataRecomputed:
    "(This node was committed without a data block; the numbers above were just re-merged from the project's " +
    "current reflection file. If the data were changed in between, they may not be the set this node was fitted to)",
  headerDataRecomputedChip: "Data recomputed",
  headerFlackTip:
    "Flack parameter (absolute structure; near 0 means the current hand is right, near 0.5 means it " +
    "cannot be decided; the e.s.d. is on the metrics tab)",
  headerSpaceGroupTip:
    "Space group (from the current scene). Olex2 puts it top right in italics because it is the most important, and most often wrong, decision on the screen",
  headerQuote: "Quote",
  headerQuoteTip:
    "Carry this card's cell, space group, R factors and data quality into the conversation, " +
    "saving typing and making sure the agent sees the numbers you are looking at",

  // crystal pane - extent (what slice of the crystal is drawn)
  modeAsu: "Asymmetric unit",
  modeAsuTip: "Draw only the independent atoms of the .res, with no symmetry expansion (where Olex2 fuse lands)",
  modeCell: "Unit cell",
  modeCellTip:
    "Fill one unit cell (Olex2 pack): finite molecules enter the cell whole by their centroid, " +
    "frameworks and chains are folded atom by atom",
  modeGrow: "Grow",
  growTip:
    "Growing is an action on the current picture, not a picture of its own (as in Olex2: pack the " +
    "cell first, then grow from it). It therefore works on any of the extents above and can be " +
    "pressed repeatedly; each press adds one shell.",
  growOnce: "Grow",
  growOnceTip: "Grow one more shell of symmetry neighbours along the bonds (Olex2 grow -s); can be repeated",
  growAtMaxTip:
    "The 4-shell display limit is reached, which does not guarantee that the molecule is complete. A periodic " +
    "framework is an infinite network; use the unit cell, a supercell or a radius extent to inspect a larger region",
  modeSuper: "Supercell",
  modeSuperTip: "Several unit cells side by side (packing, channel connectivity, interlayer relations)",
  growAll: "Grow all",
  growAllTip:
    "Keep growing along the bonds until a symmetry element the fragment has already used is met again (Olex2 grow): " +
    "finite molecules become complete (including those crossing cell boundaries or closing through symmetry); chains, layers and frameworks stop after one period, " +
    "periodic bonds get a single end cap, and the extent pill says “periodic cut”",
  growAllPeriodic: "Periodic cut",
  growAllBudget: "Atom budget cut",
  drawStyleLabel: "Style",

  // crystal pane - toolbar groups
  grpExtent: "Extent",
  secSpace: "Space",
  grpDraw: "Draw",
  elemLabel: "Elements",
  elemTip:
    "Show or hide by element (the Olex2 element row). The most useful move on a MOF is hiding C and H to see " +
    "only the metal-oxygen nodes; H follows the extent automatically, and other elements you hid stay hidden",
  grpDisplay: "Display",
  grpRelations: "Relations",
  grpRelationsTip: "Geometric relations that are not in the atom table and have to be computed",
  grpEvidence: "Evidence",
  grpEvidenceTip: "Layers that come from the experimental data rather than the model (each is computed separately; the first opening takes a moment)",
  grpView: "View",

  // crystal pane - overlays / toolbar
  ovPolyhedra: "Polyhedra",
  ovMap: "Density map",
  mapKindFofc: "Fo−Fc",
  mapKindFofcTip:
    "Difference (residual) density: green where the model lacks electrons, red where it has too many. Finds missing atoms, disorder and wrong elements",
  mapKind2fofc: "2Fo−Fc",
  mapKind2fofcTip:
    "Total density (Coot convention, blue surface): shows how well the framework density and the ligands fit, and at low " +
    "resolution whether the model keeps up with the experimental density",
  drawWire: "Wireframe",
  drawWireTip:
    "Bonds only, no spheres (Olex2 wireframe). Under grow or supercell the ball-and-stick view becomes a blur; " +
    "without spheres the connectivity and the channel directions stay readable",
  drawBall: "Ball-and-stick",
  drawBallTip: "Ball-and-stick model: small spheres coloured by element plus bond sticks (Olex2 ball&stick)",
  drawEllipsoid: "Ellipsoids",
  drawEllipsoidTip:
    "50 % probability displacement ellipsoids (anisotropic atoms; ORTEP convention). Reviewers look at these first: " +
    "flat, cigar-shaped or unusually large ellipsoids are the first sign of disorder, a wrong element or a wrong position",
  drawSpace: "Space-filling",
  drawSpaceTip:
    "Solid spheres at van der Waals radii (Olex2 spacefill): shows whether a channel is really open and " +
    "whether a guest fits, which no other representation reveals",
  ovLabels: "Labels",
  ovCapped:
    "The atom count exceeds the display limit and this layer has fallen back automatically; the switch stays on and the layer returns at a smaller extent",
  ovHbonds: "Hydrogen bonds",
  ovHbondsTip:
    "Hydrogen bonds (interaction engine): D–H···A with the Olex2 htab defaults D···A ≤ 2.9 Å and " +
    "∠D–H···A ≥ 150°; without H only D···A is reported. Riding H makes H···A systematically about " +
    "0.1–0.15 Å too long; click a dashed line for the geometry and the criteria. Partners at the edge of the extent carry a symmetry code (halo rule)",
  ovPipi: "π–π",
  ovPipiTip:
    "Aromatic ring centroids ≤ 4.0 Å apart, normals within 30°, slip ≤ 3.0 Å (Olex2 pipi defaults; " +
    "Janiak 2000); both perpendicular distances and the slip are reported, not a single number",
  ovChpi: "C–H···π",
  ovChpiTip:
    "H···ring centroid ≤ 3.2 Å, ∠C–H···Cg ≥ 120°, and the normal projection of H within the ring radius + 0.5 Å (Nishio)",
  ovChx: "C–H···X",
  ovChxTip:
    "H···A ≤ sum of the van der Waals radii, ∠C–H···A ≥ 120°, A ∈ O/N/F/Cl/S (cctbx vdW table)",
  ovHalogen: "Halogen bonds",
  ovHalogenTip:
    "X ∈ Cl/Br/I, X···Y ≤ sum of the van der Waals radii, ∠C–X···Y ≥ 155° (IUPAC 2013 σ-hole)",
  ovAnionPi: "Anion–π",
  ovAnionPiTip: "Anion centroid to ring centroid ≤ 4.5 Å with the offset within the ring radius; a weak reading, shown as a hint only",
  ixKind: {
    hbond: "Hydrogen bond",
    pipi: "π–π stacking",
    chpi: "C–H···π",
    chx: "C–H···X",
    halogen: "Halogen bond",
    anion_pi: "Anion–π",
  } as Record<string, string>,
  ixPasses: "Meets the criteria",
  ixFails: "Distance within range, angle fails the criteria",
  ixBoundary: "Partner outside the displayed extent",
  ixSymop: "Symmetry code",
  ixCriteria: "Criteria",
  ixHSource: {
    riding: "Riding H: H···A is systematically 0.1–0.15 Å too long and the angles are set by the constraint",
    refined: "H positions from refinement",
    absent: "No H: only D···A is reported; angles unavailable",
    mixed: "Some H are riding",
    unknown: "H source unknown",
  } as Record<string, string>,
  ixHaloShort: "Halo too thin: partners at the edge of the extent may be missed",
  ixTruncated: "Truncated",
  ixQuote: "Quote this interaction",
  measureClear: "Clear measurements",
  measureHint: "Click 2, 3 or 4 atoms in a row to measure a distance, an angle or a torsion",
  measureQuote: "Quote",
  measureQuoteTip:
    "Carry this measurement into the conversation (viewer readings have no e.s.d.; the agent computes one when needed)",
  ovStubs: "Grow stubs",
  ovStubsTip: "Show the clickable dangling growth directions (short dashed sticks; click a ghost sphere to grow that symmetry neighbour)",
  ovSymm: "Symmetry elements",
  ovSymmTip:
    "Space-group symmetry elements in 3D: rotation and screw axes (coloured by order, screw axes dashed), " +
    "mirror and glide planes (translucent, glides more so), inversion centres (grey dots). For special positions, " +
    "teaching and symmetry checks; symbols follow ITA (2₁, c, m, -1, …)",
  ovSlab: "Slab",
  ovSlabTip:
    "Periodic slab (VESTA style): clip the display along a, b or c by fractional coordinates to see MOF channel " +
    "cross-sections and layer profiles; density maps and pore isosurfaces are not clipped",
  slabPos: "Position",
  slabThick: "Thickness",
  ovContacts: "Short contacts",
  ovContactsTip:
    "Van der Waals short contacts (d ≤ sum of vdW radii, the Olex2 grow -s convention): generic packing neighbours, " +
    "unclassified; π–π, C–H···π, halogen bonds and so on have their own layers. Grey dashed lines join displayed atoms, " +
    "cyan ghost spheres can be clicked to grow the packing neighbour (polar pairs within hydrogen-bond distance are not repeated)",
  ovPub: "Publication style",
  ovPubTip: "White background, bold bonds, dark labels: a preset for paper figures",
  askWithView: "Ask with the view",
  askWithViewTip:
    "Attach the current view as an image to the input box with a one-line description (node, extent, layers shown), so the agent sees what you see instead of reading a description",
  exportPng: "Export image",
  exportPngTip: "Export the current view as a PNG (combine with the publication style)",
  digestNodes: "nodes",
  fuse: "Fuse",
  extentSecRange: "Extent",
  extentSecAction: "Actions",
  extentMenuTip:
    "Extent and growth: which slice of the crystal to draw and how far to grow outward (Olex2 fuse / grow / pack / compaq semantics)",
  growShell: "Grow one shell",
  growComplete: "Complete",
  growCompleteTip:
    "Apply every symmetry operator already in use to the whole asymmetric unit, so that solvent and counter-ions appear together with the grown images (Olex2 grow -w)",
  modeRadius: "Radius",
  modeRange: "Fractional box",
  packRadiusCentre: "Centre here",
  packRadiusAsu: "Asymmetric-unit centroid",
  assembleAsu: "Assemble the asymmetric unit…",
  assembleAsuTip:
    "Prefill the request in the input box; the agent calls assemble_asu (this changes the model)",
  assembleTemplate:
    "Please use assemble_asu to assemble the asymmetric unit into coherent molecules or fragments (Olex2 compaq -a semantics: fold every fragment together by symmetry). Afterwards tell me which atoms were moved and whether the bonding changed.",
  headerExpand: "Expand the structure card",
  headerCollapse: "Collapse the structure card",
  fuseTip: "Return to the ungrown state: clear shell-by-shell growth and manually added copies (Olex2 fuse)",
  partFilterLabel: "Disorder:",
  partAll: "All",
  ovPeaks: "Q peaks",
  ovPeaksTip:
    "Discrete display of the difference-density residual peaks (orange spheres, radius ∝ height): the core evidence for missing atoms, " +
    "disorder components and solvent sites; click a peak to quote it to the agent",
  peaksLoading: "Computing the Q-peak table…",
  peakNearest: "Nearest atom",
  peakQuote: "Quote this peak in the conversation",
  ovVoids: "Voids",
  ovVoidsTip:
    "Solvent-accessible void isosurface (1.2 Å probe, the Olex2/PLATON convention): " +
    "the visual basis for MOF channel connectivity and the SQUEEZE decision; each void is labelled with its volume and electron count " +
    "(note: per-void electron counts include the BYPASS rescaling; reason chemically from the whole-cell total)",
  voidsLoading: "Computing the void grid…",
  voidsNone: "This structure has no solvent-accessible voids",
  voidsQuoteTip:
    "Carry the whole-cell void volume and residual electron count into the conversation (the mask/SQUEEZE decision rests on these two numbers)",
  compareBtn: "Compare",
  compareBaselineTip: "Use this node as the comparison baseline (any two nodes)",
  compareBaselineChip: "Comparison baseline",
  compareClearTip: "Clear the comparison baseline (back to comparing with the parent)",
  ovParts: "Disorder colours",
  ovPartsTip:
    "Disorder PART groups in different colours (Olex2 part colouring), so that both orientations are distinguishable at a glance; " +
    "with labels on, PART atoms carry their occupancy",
  ovDiff: "Structure changes",
  ovSpin: "Spin",
  resetView: "Reset view",
  isoLabel: "Isosurface",

  // crystal pane - status / banner
  historyViewingPrefix: "Viewing a historical node",
  backToLatest: "Back to latest",
  sceneLoading: "Building the structure scene…",
  sceneError: "The scene failed to load",
  sceneTruncated: "Display truncated",
  sceneTruncatedTip:
    "The atom count hit the display limit, so the current picture is only part of the structure. For a periodic framework under “grow / all” this is unavoidable (an infinite network cannot be completed). Keep it in mind when judging connectivity or pores, or use the unit-cell or supercell view.",
  // distinct from "display truncated": the atoms are all drawn, but the per-cell layers
  // (voids / density map / Q peaks / symmetry elements) cover only some of the cells (round-2 R2.2, D7)
  layerRangeTruncated: (shown: number, total: number) =>
    `Layers cover ${shown} / ${total} cells`,
  layerRangeTruncatedTip:
    "The atom extent spans too many unit cells, so the per-cell layers (voids, density maps, Q peaks, symmetry elements) are laid over the cells nearest the centre only. Atoms at the edge have none of these layers next to them, which does not mean there is no void or residual density there. Shrink the extent to cover everything.",
  mapLoading: "Computing the density map (about 3 s the first time)…",
  mapError: "The density map failed to load",
  nodesLoading: "Loading nodes…",
  nodesEmpty: "This project has no refinement nodes yet",
  refreshNodes: "Refresh",

  // crystal pane - metrics / node tree
  nodeLabel: "Node",
  branchLabel: "Branch",
  atomsLabel: "Atoms",
  restraintsLabel: "Restraints",
  paramsLabel: "Parameters",
  peakLabel: "Peak",
  checkoutBtn: "Check out",
  checkoutTemplatePrefix: "Check out node ",
  checkoutTemplateSuffix: " and continue the refinement from there",
  activeTag: "Current",
  metricsTrend: "Metric trends",
  dataSectionTitle: "Data",
  dataCompleteness: "Completeness",
  dataUnique: "Unique reflections",
  dataRedundancy: "Redundancy",
  dataSpaceGroup: "Space group",
  dataShelTip: "A resolution cut-off (SHEL) is set",
  dataDminNominal: "d_min (nominal, from the data)",
  dataDminWorking: "Working cut-off (SHEL)",
  dataHklf5Tip: "The reflection file is in HKLF5 batch format (twin composite observations)",
  lineageTitle: "Lineage (to the node being viewed)",
  staleMetrics: "Awaiting refinement",
  headerInherited: "Inherited",
  headerInheritedTip:
    "This node has no measurement of its own (it was committed by a geometry operation); the metrics shown belong to the nearest ancestor that has one and are for reference only. They become this node's own once it is refined",
  treeNodesUnit: "nodes",
  treeBranchesUnit: "branches",
  treeDiagGroup: "Diagnostic branches",
  treeDiagGroupTip:
    "One-off diagnostic nodes created by tools (candidates and references from ghost_test / element_scan / probe_site), collapsed by default",
  treeFoldTip: "Fold or expand the nodes of this branch",
  treeDelivered: "Delivered",
  treeDeliveredTip: "write_outputs has delivered from this node",
  treeBestTip: "Marks the lowest value only; the nodes' comparison conditions were not checked, so this does not mean the best structure (diagnostic branches excluded)",
  treeInherited: "Inherited",
  treeInheritedTip: "This node was not refined; its R1 is inherited from the nearest refined ancestor",
  treeCompareNote: "Diagnostic branches excluded",
  treeCompareOpen: "Expand the branch comparison",
  treeCompareClose: "Collapse the branch comparison",
  staleMetricsTip:
    "The structure was modified at this node and has not been refined since; the metrics shown are from the last refinement",

  // crystal pane - selection
  selOccupancy: "Occupancy",
  selSymop: "Symmetry operation",
  selNpd: "ADP not positive definite (NPD), shown as a marker sphere",
  adpBadgeTip:
    "Abnormal displacement ellipsoids (NPD, axis ratio > 4, extreme U_eq); click to step through them and see the reason. " +
    "Often a sign that the site needs a disorder split or a corrected element assignment",
  selCenter: "Centre",
  selCenterTip: "Point the camera at this atom (centred on the selection, 0.3 s animation); reset view returns to the overview",
  selQuote: "Quote in the conversation",
  selQuotePrefix: "Look at the density and coordination around ",
  selQuoteSuffix: "",

  // artifacts panel
  openArtifact: "Open",
  previewArtifact: "Preview",
  noArtifacts: "No result files yet",
  artifactsTopLevel: "Top-level deliverables",
  artifactsMainOnly: "Main files only",
  artifactsLogs: "Run logs",
  artifactsLogsTip: "Command output and other run records; not deliverables",
  artifactsPending: "A turn is running; artifacts appear here as they are produced…",

  // settings menu (composer permission chip)
  settingsSection: "Project settings",
  settingsIucrTitle: "Allow uploads to IUCr checkCIF",
  settingsIucrDesc:
    "Allow the CIF and structure factors to be uploaded to IUCr checkcif.iucr.org (external). Off by default; when on, every submit_iucr_checkcif call by the agent still needs approval.",
  settingsSpecialistsTitle: "Enable specialist sub-agents (experimental)",
  settingsSubagentsTitle: "Read-only audit sub-agents",
  settingsSubagentsHint:
    "When on, projects at the top reasoning tier get a note in AGENTS.md that read-only audits may be delegated in parallel, and 5 read-only roles are generated in the project (each connected to its own read-only crystallography tool process; write tools are refused); lower tiers are unaffected. “Proactive at the top tier” switches the max and ultra tiers to proactive delegation at three fixed checkpoints, with a written adjudication table. Changes take effect in the next conversation.",
  settingsSubagentsActive: "Active at the current tier: roles ",
  settingsSubagentsInactive: "Not active (needs the top tier ",
  settingsSubagentsOff: "Off: no note and no roles at any tier",
  settingsSubagentsAggressive: "Proactive delegation active at the current tier (three checkpoints): roles ",
  settingsSubagentsInactiveAggressive: "Only the note at the current tier; proactive delegation needs ",
  subagentPolicyLabels: {
    top_tier: "Note at the top tier (default)",
    aggressive: "Proactive at the top tier",
    off: "Off",
  } as Record<string, string>,
  settingsSpecialistsDesc:
    "Allow the agent to consult read-only analysis specialists (space group / chemistry / density / validation / strategy) at difficult forks. Each consultation costs a full model conversation. Switching restarts this project's agent service transparently.",
  settingsSpecialistsBusy: "Waiting for the current turn to finish",

  // system rows (centered, Codex style)
  sysSpecialistsOn: "Specialist sub-agents enabled",
  sysDelegationOn:
    "Delegation tier entered: AGENTS.md carries the read-only audit delegation section and 4 read-only roles were generated in the project (effective in the next conversation)",
  sysDelegationOff:
    "Delegation tier left: the delegation section was removed and the read-only role files deleted (effective in the next conversation)",
  sysSpecialistsOff: "Specialist sub-agents disabled",
  sysPermissionPrefix: "Permission mode switched to ",
  sysRebuilt: " (agent service restarted)",
  settingsModel: "Model",
  settingsEffort: "Reasoning effort",
  // round-3 R6: knowledge mode + structure class in the settings menu
  settingsKnowledgeMode: "Knowledge mode",
  settingsKnowledgeModeHint: "Full = with the expert judgement rules; tools only = the operating contract alone (ablation control). Cannot be switched while running.",
  settingsKnowledgeModeBusy: "The knowledge mode cannot be switched while a turn is running; try again after it ends",
  knowledgeModeLabels: { full: "Full", tools_only: "Tools only" } as Record<string, string>,
  settingsStructureClass: "Structure class",
  settingsStructureClassHint: "The class you declare: the analysis tab expands its blocks by it, and the agent reads it from get_project_brief.",
  settingsStructureClassNone: "Not declared",
  settingsDefaultPrefix: "Default",
  settingsNextTurnHint: "Takes effect with the next message",
  buildStamp: "Interface build",
  buildStale:
    "Out of date: ui/src is newer than the served build; run npm run build again and restart the server",
  copyMessage: "Copy",
  copied: "Copied",

  // approvals banner
  approvalBannerSuffix: "actions awaiting approval",
  approvalJump: "View",

  // model menu (composer model button, 2026-09-07)
  modelMenuTitle: "Model",
  modelSearch: "Search models…",
  modelProviderLabel: "Provider",
  modelEffortLabel: "Reasoning effort",
  modelNoEffort: "This model has no reasoning effort levels",
  modelInCatalog: "Registered with the kernel",
  modelNotInCatalog: "Not registered with the kernel yet (registered automatically on selection; effective after an engine restart)",
  modelUnlisted: "Not in this endpoint's model list (can still be tried)",
  modelNewTag: "Unregistered",
  modelVision: "Vision",
  modelTextOnly: "Text only",
  modelContextShort: "Context",
  modelNextTurn: "Takes effect with the next message",
  modelProviderNote: "The provider is fixed when a conversation starts: after switching providers, a new conversation or a fork takes effect",
  modelForkAction: "Fork the current conversation and continue on the new provider",
  modelNewThreadAction: "New conversation",
  modelCustomId: "Custom model id…",
  modelUseId: "Use",
  modelLoading: "Loading the model list…",
  modelListError: "The model list could not be loaded",
  modelRefresh: "Refresh list",
  modelCurrent: "Current",
  modelDefaultTag: "Default",
  modelRestartPending: "The engine restarts after this turn to apply the change",
  modelEngineRestarted: "Engine restarted; the new kernel settings are in effect",
  effortNoneLabel: "None",

  // permission menu (slimmed)
  permProjectSection: "Project settings",
  subagentsSwitch: "Enable sub-agents?",
  subagentsTip:
    "On = the five read-only audit roles can be delegated to at any time and the kernel provides the sub-agent tools; off = the kernel provides no sub-agent tools. Auto: on at the top reasoning tier, otherwise off.",
  subagentsAutoLabel: "Auto",
  subagentsAutoTip: "Back to auto: on at the top tier, off elsewhere",
  subagentsStateAutoOn: "Auto · currently on (top tier)",
  subagentsStateAutoOff: "Auto · currently off",
  subagentsStateOn: "Switched on manually",
  subagentsStateOff: "Switched off manually",
  iucrTip: "Upload the CIF and structure factors to IUCr checkcif.iucr.org (external); each upload still needs approval",
  knowledgeTip: "Full = with the expert judgement rules; tools only = the operating contract alone (ablation control). Cannot be switched while running",
  structureClassTip: "Declare the crystal's class: the analysis tab expands its blocks by it and the agent reads it from the project brief",
  openSettingsLink: "More settings…",

  // settings dialog
  settingsTitle: "Settings",
  secProviders: "Providers and keys",
  secModels: "Models and reasoning",
  secContext: "Context",
  secAppearance: "Appearance",
  secAdvanced: "Advanced",
  secAbout: "About",
  providerAdd: "Add provider",
  providerNew: "New provider",
  providerId: "Identifier",
  providerIdHint: "Lowercase letters, digits and hyphens, e.g. deepseek",
  providerName: "Name",
  providerBaseUrl: "Endpoint (base URL)",
  providerBaseUrlHint: "https://openrouter.ai/api/v1",
  providerApiKey: "API key",
  providerKeyPlaceholder: "Paste the key; leave empty to keep the current one",
  providerKeySet: "Configured",
  providerKeyUnset: "Not configured",
  providerKeyUpdated: "Updated",
  providerKeyNote: "Choose a key stored on this machine, an environment variable or no authentication; sensitive values stay on this machine and are never shown again.",
  providerTest: "Check model list",
  providerTesting: "Checking…",
  providerTestOk: "Model list reachable",
  providerTestFail: "Model list unreachable",
  providerCatalogueOnly: "Model calls not verified",
  providerModelsUnit: "models",
  providerSave: "Save",
  providerSaving: "Saving…",
  providerSaved: "Saved",
  providerDelete: "Delete",
  providerEdit: "Edit",
  providerDeleteConfirm: "Delete this provider? Its key file is deactivated (recoverable from the secrets/ directory).",
  providerSetDefault: "Set as default",
  providerDefaultTag: "Default",
  providerHeaders: "Fixed request headers (one Header: Value per line; for sensitive constants use a stored key or environment headers instead)",
  providerEnvHeaders: "Request headers read from environment variables (one Header: ENV_NAME per line)",
  providerQueryParams: "Query parameters (JSON object of strings; keys and tokens are not stored here)",
  providerShowKey: "Show",
  providerHideKey: "Hide",
  providerRemoveKey: "Remove the key stored on this machine when saving",
  providerProtocol: "Protocol",
  providerNative: "Codex native",
  providerAdapterRequired: "Needs a Responses adapter",
  providerProtocolHelp: "Codex natively supports only OpenAI Responses; connect Chat, legacy Completions and Anthropic Messages through a Responses-compatible gateway.",
  providerUnsupported: "Not supported by the kernel",
  providerAuthMode: "Authentication",
  providerAuthManaged: "API key stored on this machine",
  providerAuthEnvironment: "Environment variable",
  providerAuthNone: "No authentication",
  providerAuthPreserve: "Keep the existing external authentication",
  providerAuthPreserveHelp: "This provider uses an existing command or inline authentication; ordinary edits keep it as it is, and only choosing another authentication mode replaces it.",
  providerAuthExternal: "Existing external authentication (not read)",
  providerEnvKey: "Environment variable holding the API key",
  providerEnvUnavailable: "Not set in the current process",
  providerAdvanced: "Advanced connection settings",
  providerRequestRetries: "Request retry limit",
  providerStreamRetries: "Stream retry limit",
  providerIdleTimeout: "Stream idle timeout (ms)",
  providerMapLineInvalid: "Each line must read Name: Value",
  providerMapDuplicate: "Duplicate name",
  providerQueryInvalid: "Query parameters must be a JSON object with string values only",
  providerNumberInvalid: "Enter an integer within the range",
  providerCurrentConfig: "Current configuration file",
  providerKind: "Type",
  providerKindOpenrouter: "OpenRouter",
  providerKindCompat: "Responses-compatible endpoint",
  providerUseInProject: "Use this provider for the current project",
  providerUsedByProject: "In use by the current project",
  cfgDefaultModel: "Default model",
  cfgDefaultEffort: "Default reasoning effort",
  cfgDefaultProvider: "Default provider",
  cfgNote: "These defaults apply to projects without a setting of their own. The current project's model is chosen next to the conversation input.",
  cfgSave: "Save defaults",
  ctxWindow: "Context window (tokens)",
  ctxAutoCompact: "Auto-compaction threshold (tokens)",
  ctxGlobal: "Global default",
  ctxProject: "Current project override",
  ctxHint: "Empty = the value from the model catalog; the kernel summarises and compacts automatically as the context approaches the threshold. Changes take effect after an engine restart (immediately when idle, otherwise after the turn ends).",
  ctxCompactNow: "Compact the current conversation now",
  ctxCompactSent: "Compaction requested",
  ctxCurrentUsage: "Current conversation context",
  ctxEngineNow: "Engine now",
  ctxWindowShort: "Window",
  ctxCompactShort: "Compaction threshold",
  advSpecialists: "Specialist sub-agents (experimental)",
  advSpecialistsTip: "Nested consult_specialist advisers; switching restarts this project's engine",
  advKernel: "Kernel",
  advKernelSource: "Source",
  advKernelVersion: "Version",
  advKernelPath: "Path",
  advKernelNewer: "A newer version is installed",
  advKernelUpdate: "Upgrade the kernel: run scripts/update_codex_kernel.ps1 from the command line (installs the latest official @openai/codex into vendor/codex)",
  advSdk: "Python SDK",
  advCatalog: "Model catalog",
  advCatalogCounts: "{b} built-in · {c} custom",
  advConfigPath: "Configuration file",
  advEngineRestart: "Restart the current project's engine",
  advEngineRestarting: "Restarting…",
  advOpenProjects: "Open projects",
  aboutBuild: "Interface build",
  aboutLegacy: "Legacy interface",
  settingsClose: "Close",
  settingsNoProject: "No project is open",

  // slash commands
  slashHint: "Type / to see the commands",
  slashNoMatch: "No matching command",
  slashRun: "Enter to run",
  noteStatusTitle: "Current status",
  noteMcpTitle: "Crystallography tools (MCP)",
  noteSkillsTitle: "Skills",
  noteContextTitle: "Context",
  noteMcpAbsent: "The MCP service is not mounted yet (it mounts when the first turn starts)",
  noteNoSkills: "No skills found",
  noteRenamed: "Conversation renamed",
  noteForked: "Forked into a new conversation",
  noteNeedThread: "This command must be used inside a conversation",
  noteUnknownCommand: "Unknown command; type / to see the list",

  // context / compaction
  ctxTipTitle: "Context window",
  ctxTipUsed: "Used",
  ctxTipRemaining: "Remaining",
  ctxTipTotal: "Total",
  ctxTipCompaction: "Near the limit the kernel compacts the context automatically; /compact does it now",
  ctxTipNoWindow: "This model did not report a context window size",
  railCompacting: "Compacting the context",
  sysCompactionRequested: "Context compaction requested",
  sysCompacting: "Compacting the context…",
  sysCompacted: "Context compacted: earlier content was replaced by a summary and the context usage dropped",
  sysEngineWarning: "Kernel notice: ",
  sysModelRerouted: "The kernel rerouted the model: ",
  sysEngineRestartedSettings: "Engine restarted with the new settings",

  // detached solver jobs (run_shelxt detach=true), 2026-09-18
  bgProgramSuffix: "background solution",
  bgStageStarting: "Starting",
  bgStagePhasing: "Phasing",
  bgStagePhasingGrace: "Phasing (grace period)",
  bgStageSearch: "Space-group search",
  bgStageAssign: "Element assignment",
  bgStageFinished: "Finished",
  bgStageKilled: "Stopped at the budget",
  bgStageFailed: "Failed",
  bgStageDied: "Process gone",
  bgElapsedPrefix: "elapsed",
  bgTookPrefix: "took",
  bgMinutesUnit: "min",
  bgSecondsUnit: "s",
  bgTriesUnit: "tries",
  bgBestCfom: "best CFOM",
  bgSilentSearch: "SHELXT prints nothing during this stage",
  bgSilentExhaustive: "A heavy atom was declared, so SHELXT evaluates every space group of the Laue class one by one and prints nothing during this stage",
  bgRefPrefix: "A previous search of this kind in this project took about",
  bgGroupsEvaluated: (n: number) => `${n} space groups evaluated`,
  bgSolutionUnadopted: (job: string) => `Not adopted yet; in a new turn, have the agent run run_shelxt(from_job='${job}') to adopt it`,
  bgAdopted: "Result adopted",
  bgAdoptedNode: "node",
  railBackgroundAfterTurn: "The turn has ended but the background solution is still running; the conversation will show when it finishes",
  railSolutionReady: "SHELXT solution finished, awaiting adoption",

  // sidebar / project home
  newThreadIn: "New conversations are created in",
  changeProject: "Change project",
  newThreadNoProject: "Open a project first, then start a new conversation",
  renameThread: "Rename",
  openThisProject: "Open",
  openThisProjectTip: "Switch to this project (start a new conversation on its home page)",
  openProjectHome: "Start a new conversation in this project",
  threadRenamePlaceholder: "Conversation name",
  threadRenameTip: "Rename this conversation (synced to the kernel)",
  browseFolder: "Browse…",
  browsing: "The system dialog is open…",
  browseFailed: "The system dialog could not be opened",

  // misc
  notFound: "Page not found",
  backHome: "Back to home",
  loading: "Loading…",
  emptyThread: "This conversation has no content yet",
  today: "Today",

  // punctuation used when a component composes a sentence from parts
  colon: ": ",
  sepList: ", ",
  sepClause: "; ",
  sepComma: ", ",
  paren: (inner: string | number) => ` (${inner})`,
  closeDrawer: "Close side panel",
  cmpCondComparable: "conditions comparable",
  cmpCondDifferent: "conditions differ",
  cmpCondUnknown: "conditions unknown",

  // settings dialog: section descriptions and the appearance section
  secDescProviders: "Connect model services and manage the credentials and models available on this machine.",
  secDescModels: "Choose the default model and reasoning depth, balancing capability, speed and cost.",
  secDescContext: "Control the conversation memory and when it is compacted, so long investigations stay coherent.",
  secDescAppearance: "Choose the interface language, palette, light or dark mode and reading font size.",
  secDescAdvanced: "Inspect the runtime environment and maintain a project's engine when needed.",
  secDescAbout: "CrystalPilot · keeping data, structures and the research process connected.",
  language: "Language",
  languageHint:
    "The page reloads and every part of the interface switches to the chosen language. The agent's replies follow the project's AGENTS.md, which is Chinese in this preview.",
  appPalette: "Palette",
  appPaletteNote: "Style references · unofficial themes",
  appTheme: "Theme",
  appPresentation: "Presentation mode",
  appBrandName: "Name shown top left",
  appBrandNameHint: "When on, the custom name is used; when off or empty, CrystalPilot is shown.",
  appBrandNamePlaceholder: "e.g. TopoSpace Crystal",
  providerAuthChanged: "Authentication settings changed; save before checking",

  // reasoning effort (formatEffort)
  effortLabels: {
    minimal: "Minimal",
    low: "Low",
    medium: "Medium",
    high: "High",
    xhigh: "Extra high",
    max: "Max",
    ultra: "Ultra",
  } as Record<string, string>,
};
