"""`chem/topology.py` (round-2 plan R4): interpenetration vs crystallographic
independence, node-linker simplification, the Systre `.cgd` writer and
helical chains - all on synthetic fixtures whose answer is known by
construction.

The fixtures are built element-generically (a 4-connected net of C, a
Zn/O/C pcu MOF, a Zn/O/C honeycomb layer, C helices) and every distance is
chosen so `chem.bonding`'s own criterion - sum of covalent radii + 0.45 A
for a light pair, the MetalProfile window for Zn-O - accepts the bonds of
the fixture and rejects everything else. Nothing here special-cases a real
crystal.

Geometry of the interpenetration fixtures. `expanded_dia` is a diamond net
whose edges carry one bridging atom: nodes on the two fcc sublattices,
16 bridges at the edge midpoints, 24 atoms per net. With a = 7.113 A the
node-bridge distance is 1.540 A (bonded: cutoff C-C 1.97) and the closest
approach between the net and its (1/2,1/2,1/2) copy is 1.633 x 1.540 =
2.515 A (not bonded, by the same criterion) - so the two nets really do
thread each other without touching, which a bare diamond net at any cell
edge cannot do (there the two distances are equal).
"""
from __future__ import annotations

import math

import numpy as np
import pytest
from cctbx import crystal, xray

from crystalpilot.chem.topology import (DEF_HELIX, DEF_NETS, DEF_SIMPLIFIED,
                                        helices, independent_nets, run_systre,
                                        simplified_net, systre_jar, write_cgd)

# --------------------------------------------------------------- fixtures --

A_DIA = 7.113                    # node-bridge 1.540 A in the expanded dia
FCC = [np.array(p, float) for p in
       [(0, 0, 0), (0, .5, .5), (.5, 0, .5), (.5, .5, 0)]]
TETRA = [np.array(v, float) * .25 for v in
         [(1, 1, 1), (1, -1, -1), (-1, 1, -1), (-1, -1, 1)]]
DIA_CELL = (A_DIA, A_DIA, A_DIA, 90, 90, 90)


def _structure(atoms, cell, sg="P 1", cart=False):
    """atoms: (label, element, xyz) - fractional unless `cart`."""
    cs = crystal.symmetry(unit_cell=cell, space_group_symbol=sg)
    xs = xray.structure(crystal_symmetry=cs)
    uc = cs.unit_cell()
    for label, el, xyz in atoms:
        site = uc.fractionalize(tuple(xyz)) if cart else tuple(xyz)
        xs.add_scatterer(xray.scatterer(label=label, site=site,
                                        scattering_type=el, u=0.02))
    xs.scattering_type_registry(table="it1992")
    return xs


def expanded_dia(node="C", node2=None, bridge="C", offset=(0, 0, 0), tag=""):
    """One 4-connected (diamond) net with one bridging atom per edge.

    `node` / `node2` are the two fcc sublattices (equal for a one-element
    net, different for a non-centrosymmetric binary net), `bridge` sits at
    every edge midpoint. 24 atoms.
    """
    node2 = node2 or node
    off = np.array(offset, float)
    out, n = [], 0
    for p in FCC:
        n += 1
        out.append((f"{node}{tag}{n}", node, tuple((p + off) % 1.0)))
    for p in FCC:
        n += 1
        out.append((f"{node2}{tag}{n}", node2, tuple((p + .25 + off) % 1.0)))
    seen = set()
    for p in FCC:
        for d in TETRA:
            q = (p + d / 2.0 + off) % 1.0
            key = tuple(np.round(q, 6))
            if key in seen:
                continue
            seen.add(key)
            n += 1
            out.append((f"{bridge}{tag}{n}", bridge, tuple(q)))
    return out


def one_net():
    return _structure(expanded_dia(), DIA_CELL)


def two_nets_by_translation():
    """The net and its (1/2,1/2,1/2) copy, both spelled out in P1."""
    return _structure(expanded_dia()
                      + expanded_dia(offset=(.5, .5, .5), tag="B"), DIA_CELL)


def two_independent_nets():
    """A C net and an N net of a DIFFERENT size (one bridge removed): no
    operator can map one onto the other, so they are crystallographically
    independent, not interpenetrating."""
    other = expanded_dia(node="N", bridge="N", offset=(.5, .5, .5),
                         tag="B")[:-1]
    return _structure(expanded_dia() + other, DIA_CELL)


def two_nets_by_inversion():
    """P-1, ONE net in the asymmetric unit, the second generated by the
    inversion centre.

    The net has to be non-centrosymmetric for this to be a real test: a
    plain diamond net is centrosymmetric about its bond midpoint, so its
    inversion image is only a TRANSLATE of itself. Decorating the two fcc
    sublattices with different elements (C / N, bridges O) removes the
    inversion, and the whole net is offset by (1/8,1/8,1/8) so the image
    does not land on top of the original.
    """
    return _structure(expanded_dia(node="C", node2="N", bridge="O",
                                   offset=(.125, .125, .125)),
                      DIA_CELL, sg="P -1")


def pcu_mof():
    """Zn at the cell corner of a 10 A cube, an O-C-C-C-O linker along each
    axis: Zn-O 2.00 (inside the Zn-O window 1.85-2.45), O-C 1.30,
    C-C 1.70. Every Zn is 6-connected, every linker bridges the corner to
    the next cell's corner -> the pcu net."""
    atoms = [("ZN1", "Zn", (0, 0, 0))]
    n = 0
    for axis in range(3):
        for d, el in ((2.0, "O"), (3.3, "C"), (5.0, "C"), (6.7, "C"),
                      (8.0, "O")):
            n += 1
            p = [0.0, 0.0, 0.0]
            p[axis] = d
            atoms.append((f"{el}{n}", el, tuple(p)))
    return _structure(atoms, (10.0, 10.0, 10.0, 90, 90, 90), cart=True)


def hcb_mof():
    """A honeycomb layer: a 3-connected Zn and a 3-connected tritopic
    linker. The linker centre C0 carries three C-O arms, each reaching a
    DIFFERENT Zn image (C0-C 1.40, C-O 1.30, O-Zn 2.30), so the linker
    touches three metal clusters and becomes a node itself."""
    a = 5.0 * math.sqrt(3.0)          # vertex-vertex = a/sqrt(3) = 5.0 A
    centre = np.array([2 / 3, 1 / 3, 0.0])
    arms = [np.array([-1 / 3, 1 / 3, 0.0]), np.array([2 / 3, 1 / 3, 0.0]),
            np.array([-1 / 3, -2 / 3, 0.0])]
    atoms = [("ZN1", "Zn", tuple(np.array([1 / 3, 2 / 3, 0.0]))),
             ("C0", "C", tuple(centre))]
    for k, v in enumerate(arms, start=1):
        atoms.append((f"C{k}", "C", tuple(centre + v * (1.4 / 5.0))))
        atoms.append((f"O{k}", "O", tuple(centre + v * (2.7 / 5.0))))
    return _structure(atoms, (a, a, 20.0, 90, 90, 120))


def molecular_crystal():
    """A discrete organic molecule (no metals, dim 0): a C6 ring of 1.40 A
    bonds in a 20 A box."""
    atoms = []
    for k in range(6):
        ang = k * math.pi / 3.0
        atoms.append((f"C{k + 1}", "C",
                      (1.40 * math.cos(ang), 1.40 * math.sin(ang), 0.0)))
    return _structure(atoms, (20.0, 20.0, 20.0, 90, 90, 90), cart=True)


C_HELIX = 6.0
R_HELIX = math.sqrt(1.50 ** 2 - (C_HELIX / 6.0) ** 2)     # 1.118 A


def screw_chain(sg, order, cell, radius, sense=1, axis=(0.0, 0.0)):
    """Two atoms per screw step around the c axis at fractional `axis`.

    A one-atom asymmetric unit cannot be used: `chem.bonding.bond_table`
    returns no edges for a structure with fewer than two scatterers. With
    two atoms half a screw step apart the chain is C1-C2-C1'-C2'... at
    1.50 A, the next-nearest pair is 2.78 A and the c repeat is 6.0 A, so
    only the helix is bonded.
    """
    cs = crystal.symmetry(unit_cell=cell, space_group_symbol=sg)
    uc = cs.unit_cell()
    half = sense * math.pi / order
    p0 = np.array(uc.fractionalize((radius, 0.0, 0.0)))
    p1 = np.array(uc.fractionalize((radius * math.cos(half),
                                    radius * math.sin(half),
                                    cell[2] / (2.0 * order))))
    base = np.array([axis[0], axis[1], 0.0])
    return _structure([("C1", "C", tuple(base + p0)),
                       ("C2", "C", tuple(base + p1))], cell, sg=sg)


def helix_31():
    return screw_chain("P 31", 3, (12, 12, C_HELIX, 90, 90, 120), R_HELIX)


def helix_32():
    return screw_chain("P 32", 3, (12, 12, C_HELIX, 90, 90, 120), R_HELIX,
                       sense=-1)


def helix_racemic():
    """R-3: centrosymmetric, and BOTH hands are present.

    No centrosymmetric group contains a 3_1 axis at the origin (3_1 and
    3_2 about one axis would force (0,0,2/3) into the lattice), but the
    rhombohedral centring turns the pure 3 into 3_1 axes at (1/3,1/3,z)
    and 3_2 axes at (2/3,2/3,z), and the inversion exchanges them - so a
    chain wound on a 3_1 axis has a 3_2 partner in the same cell.
    """
    return screw_chain("R -3 :H", 3, (30, 30, C_HELIX, 90, 90, 120), R_HELIX,
                       axis=(1 / 3, 1 / 3))


def helix_21():
    """A 2_1 zig-zag along b: C1 at (0.5, 0, 0) A, C2 at (-0.5, 1.3, 0) A,
    b = 5.88, so C1-C2 = 1.60 and C2-(2_1 C1) = 1.64 while the b repeat
    (5.88) and the C1...2_1C1 pair (3.11) stay unbonded."""
    return _structure([("C1", "C", (0.5, 0.0, 0.0)),
                       ("C2", "C", (-0.5, 1.3, 0.0))],
                      (10.0, 5.88, 10.0, 90, 90, 90), sg="P 21", cart=True)


def straight_chain():
    """A P1 chain of C along c at 1.50 A: 1-D, no screw anywhere."""
    return _structure([("C1", "C", (0.0, 0.0, 0.0)),
                       ("C2", "C", (0.0, 0.0, 1.5))],
                      (10.0, 10.0, 3.0, 90, 90, 90), cart=True)


# ------------------------------------------------- 1. independent nets -----

class TestIndependentNets:
    def test_single_net(self):
        r = independent_nets(one_net())
        assert r["n_nets"] == 1
        assert r["nets"][0]["dimensionality"] == 3
        assert r["nets"][0]["n_atoms_p1"] == 24
        assert r["relations"] == []
        assert r["interpenetrated"] is False
        assert r["interlocked_1d"] is False

    def test_translation_related_copy_is_interpenetration(self):
        r = independent_nets(two_nets_by_translation())
        assert r["n_nets"] == 2
        assert [n["dimensionality"] for n in r["nets"]] == [3, 3]
        assert [n["n_atoms_p1"] for n in r["nets"]] == [24, 24]
        assert r["relations"] == [{"a": 1, "b": 2, "relation": "translation",
                                   "op": None, "shift": [0.5, 0.5, 0.5]}]
        assert r["symmetry_related"] is True
        # round-3 R5: DECIDED by ring threading - every 6-ring window of
        # either diamond net is crossed by a bond of the other
        assert r["interpenetrated"] is True
        assert r["interlocked_1d"] is None            # no 1-D pair to test
        assert r["interpenetration_status"] == "tested"
        pair = r["threading"]["pairs"][0]
        assert pair["status"] == "threaded" and pair["dims"] == [3, 3]
        # the diamond net has 12 six-membered windows per conventional cell
        assert pair["a_windows"] == 12 and pair["a_windows_threaded_by_b"] == 12
        assert pair["b_windows"] == 12 and pair["b_windows_threaded_by_a"] == 12
        assert pair["truncated"] is False
        assert pair["example"]["window_size"] == 6
        assert len(pair["example"]["bond"]) == 2
        assert pair["rule"] == ["branch_points", "branch_points"]
        assert r["threading"]["max_ring_size"] == 12
        assert any("环穿越判定" in n and "互穿" in n for n in r["notes"])

    def test_two_different_nets_are_independent_yet_threaded(self):
        """No operator maps the C net onto the N net (one bridge short), so
        they are crystallographically independent - and they still thread
        each other, which is what the geometric test is for."""
        r = independent_nets(two_independent_nets())
        assert r["n_nets"] == 2
        assert [n["n_atoms_p1"] for n in r["nets"]] == [24, 23]
        assert r["relations"][0]["relation"] == "independent"
        assert r["relations"][0]["op"] is None
        assert r["relations"][0]["shift"] is None
        assert r["symmetry_related"] is False
        assert r["interpenetrated"] is True
        assert r["interpenetration_status"] == "tested"

    def test_symmetry_generated_second_net_names_the_operator(self):
        r = independent_nets(two_nets_by_inversion())
        assert r["n_nets"] == 2
        assert [n["dimensionality"] for n in r["nets"]] == [3, 3]
        rel = r["relations"][0]
        assert rel["relation"] == "space_group_op"
        assert rel["op"] == "-x,-y,-z"
        assert rel["shift"] == [0.0, 0.0, 0.0]
        assert r["symmetry_related"] is True
        assert r["interpenetrated"] is True

    def test_one_dimensional_nets_are_interlocked_not_interpenetrated(self):
        """Six symmetry-related helices per cell: the dim-1 case is named
        interlocked_1d and never reported as interpenetration."""
        r = independent_nets(helix_racemic())
        assert r["n_nets"] == 6
        assert {n["dimensionality"] for n in r["nets"]} == {1}
        assert {tuple(n["direction"]) for n in r["nets"]} == {(0, 0, 1)}
        assert r["symmetry_related_1d"] is True
        assert r["interpenetrated"] is None
        # helices have no rings: a ring-threading test cannot see how they
        # wind around each other, and says so instead of guessing
        assert r["interlocked_1d"] is None
        assert r["interpenetration_status"] == "not_testable"
        assert all(p["status"] == "not_testable" for p in r["threading"]["pairs"])
        assert any("没有环" in n for n in r["notes"])

    def test_molecular_crystal_has_no_nets(self):
        r = independent_nets(molecular_crystal())
        assert r["n_nets"] == 0
        assert r["interpenetrated"] is False

    def test_parallel_square_layers_do_not_prove_interpenetration(self):
        xs = _structure([("C1", "C", (0, 0, 0.25)),
                         ("C2", "C", (0, 0, 0.75))],
                        (1.54, 1.54, 10, 90, 90, 90))
        r = independent_nets(xs)
        assert r["n_nets"] == 2
        assert [n["dimensionality"] for n in r["nets"]] == [2, 2]
        assert r["symmetry_related"] is True
        # round-3 R5: the counterexample the symmetry test cannot settle -
        # the layers map onto each other and are NOT interpenetrated: no
        # bond of one layer crosses a square window of the other
        assert r["interpenetrated"] is False
        assert r["interpenetration_status"] == "tested"
        pair = r["threading"]["pairs"][0]
        assert pair["status"] == "not_threaded"
        assert pair["a_windows"] == 1 and pair["a_windows_threaded_by_b"] == 0
        assert any("不互穿" in note for note in r["notes"])

    def test_threading_budget_exhaustion_is_null_with_a_reason(self):
        r = independent_nets(two_nets_by_translation(), threading_budget_s=-1.0)
        assert r["interpenetrated"] is None
        assert r["interpenetration_status"] == "inconclusive"
        pair = r["threading"]["pairs"][0]
        assert pair["status"] == "inconclusive" and "budget" in pair["reason"]
        assert any("未完成" in note for note in r["notes"])

    def test_windows_of_the_contracted_graphs(self):
        """The ring finder on its own: a pcu node with three loop edges has
        exactly three 4-windows (the 6-cycles through a straight angle fail
        the shortest-path criterion); a diamond net of 8 nodes has twelve
        6-windows."""
        from crystalpilot.chem import threading as thr
        rings, trunc = thr.rings_of(1, [(0, 0, (1, 0, 0)), (0, 0, (0, 1, 0)),
                                        (0, 0, (0, 0, 1))])
        assert not trunc
        assert sorted(len(r) for r in rings) == [4, 4, 4]
        from crystalpilot.chem.topology import _p1_graph
        g = _p1_graph(one_net())
        c = thr.contract(g, range(g["n"]), set())
        assert c["rule"] == "branch_points" and len(c["nodes"]) == 8
        assert len(c["edges"]) == 16 and c["rods"] == 0
        rings, trunc = thr.rings_of(len(c["nodes"]), c["edges"])
        assert not trunc and len(rings) == 12
        assert {len(r) for r in rings} == {6}

    def test_definition_travels_with_the_answer(self):
        r = independent_nets(one_net())
        assert r["definition"] == DEF_NETS
        assert "互穿" in r["definition"] and "independent" in r["definition"]
        assert "NOT proof of interpenetration" in r["definition_en"]


# ------------------------------------------- 2. node-linker simplification --

class TestSimplifiedNet:
    def test_pcu_mof(self):
        r = simplified_net(pcu_mof())
        assert r["n_nodes_per_cell"] == 1
        assert r["n_edges_per_cell"] == 3
        assert r["node_connectivity_histogram"] == {6: 1}
        node = r["nodes"][0]
        assert node["kind"] == "metal_cluster"
        assert node["atoms"] == ["ZN1"]
        assert node["connectivity"] == 6
        assert node["centroid_frac"] == [0.0, 0.0, 0.0]
        assert r["edges"] == [[1, 1, [1, 0, 0]], [1, 1, [0, 1, 0]],
                              [1, 1, [0, 0, 1]]]
        assert [lk["n_nodes_touched"] for lk in r["linkers"]] == [2, 2, 2]
        assert {lk["role"] for lk in r["linkers"]} == {"edge"}

    def test_three_connected_linker_becomes_a_node(self):
        r = simplified_net(hcb_mof())
        assert r["n_nodes_per_cell"] == 2
        assert r["n_edges_per_cell"] == 3
        assert r["node_connectivity_histogram"] == {3: 2}
        kinds = {n["kind"]: n for n in r["nodes"]}
        assert set(kinds) == {"metal_cluster", "branch_linker"}
        assert kinds["metal_cluster"]["atoms"] == ["ZN1"]
        assert kinds["branch_linker"]["atoms"] == [
            "C0", "C1", "C2", "C3", "O1", "O2", "O3"]
        assert kinds["branch_linker"]["connectivity"] == 3
        assert r["linkers"][0]["n_nodes_touched"] == 3
        assert r["linkers"][0]["role"] == "node"
        assert "≥3" in r["confidence"]

    def test_molecular_crystal_returns_no_nodes_with_a_note(self):
        r = simplified_net(molecular_crystal())
        assert r["nodes"] == [] and r["edges"] == []
        assert r["n_nodes_per_cell"] == 0 and r["n_edges_per_cell"] == 0
        assert r["node_connectivity_histogram"] == {}
        assert "没有金属" in r["note"] and "分子晶体" in r["note"]

    def test_definition_and_confidence_travel_with_the_answer(self):
        r = simplified_net(pcu_mof())
        assert r["definition"] == DEF_SIMPLIFIED
        assert "描述" in r["definition"] and "判定" in r["definition"]
        assert "不是判定" in r["confidence"]


# --------------------------------------------------- 3. Systre bridge ------

class TestSystreBridge:
    def test_pcu_cgd_is_the_standard_one(self):
        r = simplified_net(pcu_mof())
        assert write_cgd(r, "pcu") == (
            "PERIODIC_GRAPH\n"
            "  NAME pcu\n"
            "  EDGES\n"
            "    1 1 1 0 0\n"
            "    1 1 0 1 0\n"
            "    1 1 0 0 1\n"
            "END\n")

    def test_cgd_edge_order_is_deterministic(self):
        """Same net, edges handed over shuffled: same text."""
        r = simplified_net(pcu_mof())
        shuffled = {"edges": [[1, 1, [0, 0, -1]], [1, 1, [0, 1, 0]],
                              [1, 1, [-1, 0, 0]]]}
        assert write_cgd(shuffled, "pcu") == write_cgd(r, "pcu")

    def test_hcb_cgd_names_both_vertices(self):
        text = write_cgd(simplified_net(hcb_mof()), "hcb")
        assert text.startswith("PERIODIC_GRAPH\n  NAME hcb\n  EDGES\n")
        edges = [ln.split() for ln in text.splitlines()[3:-1]]
        assert len(edges) == 3
        assert all(e[:2] == ["1", "2"] for e in edges)

    def test_runner_is_gated_and_never_raises(self):
        if systre_jar() is not None:
            pytest.skip("a Gavrog jar is installed - the gated path is moot")
        out = run_systre(write_cgd(simplified_net(pcu_mof()), "pcu"))
        assert out["rcsr_symbol"] is None
        assert out["rcsr_status"].startswith("未算（未安装 Systre）")
        assert out["systre_output"] is None

    @pytest.mark.skipif(systre_jar() is None,
                        reason="no vendor/gavrog/*.jar installed")
    def test_systre_names_pcu(self):
        out = run_systre(write_cgd(simplified_net(pcu_mof()), "pcu"))
        assert out["rcsr_symbol"] == "pcu", out["systre_output"]


# --------------------------------------------------------- 4. helices -----

class TestHelices:
    def test_p31_is_right_handed_with_pitch_c(self):
        h = helices(helix_31())
        assert len(h) == 1
        assert h[0]["dimensionality"] == 1
        assert h[0]["axis_direction"] == [0, 0, 1]
        assert h[0]["screw"] == "3_1" and h[0]["order"] == 3
        assert h[0]["handedness"] == "right"
        assert h[0]["pitch_A"] == pytest.approx(C_HELIX)
        assert h[0]["racemic"] is False
        assert h[0]["definition"] == DEF_HELIX

    def test_p32_is_left_handed_with_the_same_pitch(self):
        h = helices(helix_32())
        assert len(h) == 1
        assert h[0]["screw"] == "3_2"
        assert h[0]["handedness"] == "left"
        assert h[0]["pitch_A"] == pytest.approx(C_HELIX)
        assert h[0]["racemic"] is False

    def test_21_screw_has_no_handedness(self):
        h = helices(helix_21())
        assert len(h) == 1
        assert h[0]["screw"] == "2_1" and h[0]["order"] == 2
        assert h[0]["axis_direction"] == [0, 1, 0]
        assert h[0]["handedness"] is None
        assert h[0]["pitch_A"] == pytest.approx(5.88)
        assert "没有手性" in h[0]["note"]

    def test_straight_chain_is_not_helical(self):
        assert helices(straight_chain()) == []

    def test_centrosymmetric_group_is_racemic(self):
        h = helices(helix_racemic())
        assert {e["screw"] for e in h} == {"3_1", "3_2"}
        assert all(e["racemic"] is True for e in h)
        assert all(e["handedness"] is None for e in h)
        assert all(e["pitch_A"] == pytest.approx(C_HELIX) for e in h)
        assert all("外消旋" in e["note"] for e in h)

    def test_a_framework_has_no_one_dimensional_fragment(self):
        assert helices(pcu_mof()) == []
