"""interpret_peaks without a metal: density tiers instead of M-O windows.

Before T1.2 every structure went through the metal-coordination lens.
`metals` was "is_metal(el) or Z >= 17", so a chloride salt was solved as
if the Cl were a metal centre and every peak 1.8-2.6 A from it became an
O; a pure organic got NO oxygen at all (no metal -> no M-O window -> all
C). Both are the same mistake: reading an organic through MOF chemistry.

The cases below are built from synthetic structures of four different
types (nothing here is tuned to one crystal): the peak list handed to
the tool is a REAL peak search of the structure's own Fc density, and
the tiers are read from real integrated densities in 0.7 A spheres.
"""
from __future__ import annotations

import math

import pytest
from cctbx import crystal, maptbx, xray
from cctbx.array_family import flex

from crystalpilot.core.dataset import CompositionHint, ReflectionDataset
from crystalpilot.pipeline.session import SolveSession
from crystalpilot.tools import solution_tools as st
from crystalpilot.tools.base import ToolContext
from crystalpilot.tools.model_tools import InterpretPeaks


class _Store:
    def emit(self, *a, **k):
        return None

    def record(self, *a, **k):
        return None

    def log(self, *a, **k):
        return None


def _structure(cell, sg, atoms):
    cs = crystal.symmetry(unit_cell=cell, space_group_symbol=sg)
    xs = xray.structure(crystal_symmetry=cs)
    uc = cs.unit_cell()
    for label, el, cart in atoms:
        xs.add_scatterer(xray.scatterer(
            label=label, site=uc.fractionalize(cart), scattering_type=el,
            u=0.025))
    xs.scattering_type_registry(table="it1992")
    return xs


def _solved_session(xs, elements: dict[str, float], z: float,
                    d_min: float = 0.85) -> SolveSession:
    """A session that looks exactly like one a solver just left behind.

    The peak list is a real peak search of the structure's own density
    and the per-peak densities are real 0.7 A sphere integrals - the same
    two numbers solve_charge_flipping now stores in cf_info.
    """
    cs = xs.crystal_symmetry()
    f_calc = xs.structure_factors(d_min=d_min).f_calc()
    fo_sq = f_calc.intensities().customized_copy(
        sigmas=flex.double(f_calc.size(), 1.0)
    ).set_observation_type_xray_intensity()
    fft_map = f_calc.fft_map(symmetry_flags=maptbx.use_space_group_symmetry)
    fft_map.apply_volume_scaling()
    peaks = fft_map.peak_search(
        maptbx.peak_search_parameters(
            interpolate=True, min_distance_sym_equiv=0.8,
            min_cross_distance=0.9,
            max_clusters=int(xs.scatterers().size() * 2) + 8),
        verify_symmetry=False).all()
    sites = list(peaks.sites())
    heights = list(peaks.heights())
    integrated = st._peak_density(fft_map.real_map_unpadded(),
                                  cs.unit_cell(), sites)
    ses = SolveSession(dataset=ReflectionDataset(
        intensities=None, wavelength=0.71073,
        composition=CompositionHint(elements=dict(elements), z=z,
                                    source="unit test")))
    ses.symmetry = cs
    ses.fo_sq = fo_sq
    ses.merge_info = {"d_min": round(fo_sq.d_min(), 3),
                      "completeness": round(
                          fo_sq.completeness(d_max=float("inf")), 3)}
    ses.cf_info = {
        "d_min": d_min, "peak_sites": sites, "peak_heights": heights,
        **({"peak_integrated_density": [round(v, 3) for v in integrated],
            "peak_density_radius_A": st.PEAK_DENSITY_RADIUS_A,
            "peak_density_units": "electrons (volume-scaled map)"}
           if integrated else {})}
    return ses


def _run(ses, **params):
    r = InterpretPeaks().run(ToolContext(store=_Store(), session=ses),
                             **params)
    assert r.ok, r.error
    return r.summary


def _rows(summary):
    return {row["atom"]: row for row in summary["element_assignment"]}


# --------------------------------------------------------------------- #
# fixtures: four different chemistries, none of them a MOF
# --------------------------------------------------------------------- #

def _benzoic_acid_dimer():
    """The R2,2(8) carboxylic-acid dimer, both halves written out in P1.

    Ideal geometry: 1.39 A aromatic ring bonds, a 1.48 A ring-to-carboxyl
    bond, a 1.23 A C=O and a 1.31 A C-OH, the second molecule generated by
    inverting the first through the point between the two carboxyls (the
    classic hydrogen-bonded dimer, here at O...O 2.99 A).
    """
    mol = []
    r, cx0, cy = 1.39, 4.0, 5.0
    for k in range(6):
        a = math.radians(60 * k)
        mol.append(("C", (cx0 + r * math.cos(a), cy + r * math.sin(a), 5.0)))
    cx = cx0 + r + 1.48
    mol.append(("C", (cx, cy, 5.0)))
    mol.append(("O", (cx + 1.23 * math.cos(math.radians(60)),
                      cy + 1.23 * math.sin(math.radians(60)), 5.0)))
    mol.append(("O", (cx + 1.31 * math.cos(math.radians(-60)),
                      cy + 1.31 * math.sin(math.radians(-60)), 5.0)))
    centre = (9.0, 4.965, 5.0)
    atoms, n = [], {"C": 0, "O": 0}
    for half in (1, -1):
        for el, cart in mol:
            n[el] += 1
            p = cart if half == 1 else tuple(2 * c - x
                                             for c, x in zip(centre, cart))
            atoms.append((f"{el}{n[el]}", el, p))
    return _structure((17.0, 14.0, 12.0, 90, 90, 90), "P 1", atoms)


def _dbu_hcl_like():
    """A bicyclic amidinium cation plus a free chloride.

    9 skeletal carbons (the tool must not type the two nitrogens), one
    chloride with no covalent partner - the DBU.HCl motif. Chemistry, not
    a copy of any particular crystal.
    """
    atoms = []
    # amidinium head: a short delocalised C-N pair drawn as skeleton atoms
    ring = [(4.20, 4.00, 4.00), (5.60, 4.35, 4.20), (6.35, 3.20, 4.70),
            (5.60, 1.95, 4.30), (4.20, 2.05, 4.55), (3.50, 3.15, 5.05),
            (7.70, 3.30, 4.10), (8.30, 4.60, 4.60), (7.35, 5.55, 5.20)]
    for k, cart in enumerate(ring):
        atoms.append((f"C{k + 1}", "C", cart))
    atoms.append(("CL1", "Cl", (1.20, 7.60, 8.40)))
    return _structure((11.5, 12.5, 13.5, 90, 103.0, 90), "P 1", atoms)


def _cu_paddlewheel():
    """Cu2(O2CR)4 fragment: the metal branch must be untouched by T1.2."""
    atoms = [("CU1", "Cu", (5.00, 5.00, 4.70)),
             ("CU2", "Cu", (5.00, 5.00, 7.30))]
    for k, (dx, dy) in enumerate(((1.97, 0.0), (-1.97, 0.0),
                                  (0.0, 1.97), (0.0, -1.97))):
        atoms.append((f"O{2 * k + 1}", "O", (5.0 + dx, 5.0 + dy, 4.85)))
        atoms.append((f"O{2 * k + 2}", "O", (5.0 + dx, 5.0 + dy, 7.15)))
        atoms.append((f"C{k + 1}", "C",
                      (5.0 + dx * 1.42, 5.0 + dy * 1.42, 6.00)))
    return _structure((14.0, 14.0, 15.0, 90, 90, 90), "P 1", atoms)


def _thiophene_like():
    """2-acetylthiophene: S is an anchor and a ring member, never a metal.

    Ring from the microwave geometry (S-C 1.714, C-S-C 92.2 deg, C2-C3
    1.370, C3-C4 1.423), acetyl group at C2 with a 1.22 A C=O.
    """
    o = (4.0, 3.0, 4.0)

    def at(x, y):
        return (o[0] + x, o[1] + y, o[2])

    half = math.radians(46.1)
    c2 = (1.714 * math.sin(half), 1.714 * math.cos(half))
    c5 = (-c2[0], c2[1])
    # S-C2-C3 111.5 deg, C2-C3 1.370: rotate the C2->S bond into place
    ux, uy = (-c2[0] / 1.714, -c2[1] / 1.714)
    th = math.radians(-111.5)
    dx = ux * math.cos(th) - uy * math.sin(th)
    dy = ux * math.sin(th) + uy * math.cos(th)
    c3 = (c2[0] + 1.370 * dx, c2[1] + 1.370 * dy)
    c4 = (-c3[0], c3[1])
    # acetyl on C2, pointing away from the ring centre
    cen = ((0 + c2[0] + c3[0] + c4[0] + c5[0]) / 5,
           (0 + c2[1] + c3[1] + c4[1] + c5[1]) / 5)
    vx, vy = c2[0] - cen[0], c2[1] - cen[1]
    vn = math.hypot(vx, vy)
    vx, vy = vx / vn, vy / vn
    ca = (c2[0] + 1.47 * vx, c2[1] + 1.47 * vy)
    bx, by = -vx, -vy                       # ca -> c2
    for ang, dist, out in ((-120.0, 1.22, "o"), (120.0, 1.50, "me")):
        t = math.radians(ang)
        px = bx * math.cos(t) - by * math.sin(t)
        py = bx * math.sin(t) + by * math.cos(t)
        if out == "o":
            oc = (ca[0] + dist * px, ca[1] + dist * py)
        else:
            me = (ca[0] + dist * px, ca[1] + dist * py)
    atoms = [("S1", "S", at(0.0, 0.0)),
             ("C1", "C", at(*c2)), ("C2", "C", at(*c3)),
             ("C3", "C", at(*c4)), ("C4", "C", at(*c5)),
             ("C5", "C", at(*ca)), ("O1", "O", at(*oc)),
             ("C6", "C", at(*me))]
    return _structure((12.0, 13.0, 10.5, 90, 95.0, 90), "P 1", atoms)


# --------------------------------------------------------------------- #
# 1. metal-free organic: O by tier, C/N never guessed
# --------------------------------------------------------------------- #

@pytest.fixture(scope="module")
def summary_benzoic():
    return _run(_solved_session(_benzoic_acid_dimer(),
                                {"C": 7, "H": 6, "O": 2}, z=2))


@pytest.fixture(scope="module")
def summary_chloride():
    return _run(_solved_session(_dbu_hcl_like(),
                                {"C": 9, "H": 17, "N": 2, "Cl": 1}, z=1))


@pytest.fixture(scope="module")
def summary_paddlewheel():
    return _run(_solved_session(_cu_paddlewheel(),
                                {"Cu": 2, "C": 4, "O": 8}, z=1))


@pytest.fixture(scope="module")
def summary_thiophene():
    return _run(_solved_session(_thiophene_like(),
                                {"C": 6, "H": 6, "O": 1, "S": 1}, z=1))


class TestBenzoicAcidDimer:

    def test_takes_the_metal_free_branch(self, summary_benzoic):
        assert summary_benzoic["branch"] == "metal_free_density_tier"
        assert "0.7 A sphere" in summary_benzoic["density_measure"]
        assert summary_benzoic["density_units"].startswith("electrons")

    def test_oxygen_is_found_by_density_tier(self, summary_benzoic):
        assert summary_benzoic["element_counts"].get("O") == 4, summary_benzoic
        rows = _rows(summary_benzoic)
        for lbl, row in rows.items():
            if row["element"] == "O":
                assert row["density_ratio"] >= 1.15, row
                assert "tier line" in row["reason"]

    def test_carbon_sites_are_never_claimed(self, summary_benzoic):
        rows = _rows(summary_benzoic)
        carbons = [r for r in rows.values() if r["element"] == "C"]
        assert carbons
        assert all(r["element_uncertain"] for r in carbons), carbons
        assert all(r["element_confidence"] in ("low", "medium")
                   for r in carbons)
        assert summary_benzoic["n_element_uncertain"] >= len(carbons)

    def test_nitrogen_budget_is_disclosure_only(self, summary_benzoic):
        nb = summary_benzoic["nitrogen_budget"]
        assert nb["n_assigned"] == 0
        assert nb["n_allowed_per_asu"] == 0.0
        assert "N" not in summary_benzoic["element_counts"]

    def test_chem_hint_reads_the_organic_motifs(self, summary_benzoic):
        motifs = {m["motif"] for m in summary_benzoic["chem_hint"]["motifs"]}
        assert "aromatic_ring" in motifs, summary_benzoic["chem_hint"]
        assert motifs & {"carboxylate", "carboxylic_acid_or_ester"}, motifs
        # every motif has to say WHY, in distances
        for m in summary_benzoic["chem_hint"]["motifs"]:
            assert " A" in m["evidence"], m


# --------------------------------------------------------------------- #
# 2. organic salt with a heavy NON-metal: Cl is an anchor, not a centre
# --------------------------------------------------------------------- #

class TestOrganicChlorideSalt:

    def test_chloride_does_not_make_it_a_metal_case(self, summary_chloride):
        assert summary_chloride["branch"] == "metal_free_density_tier"
        assert summary_chloride["element_counts"].get("Cl") == 1, summary_chloride
        rows = _rows(summary_chloride)
        cl = [r for r in rows.values() if r["element"] == "Cl"][0]
        assert cl["density_ratio"] >= 1.68, cl        # the C/Cl tier line
        assert cl["element_confidence"] == "high"
        assert cl["element_uncertain"] is False

    def test_no_oxygen_is_invented_around_the_chloride(self, summary_chloride):
        # the old branch called every peak 1.8-2.6 A from the "metal" an O
        assert "O" not in summary_chloride["element_counts"], summary_chloride

    def test_the_two_nitrogens_are_disclosed_not_placed(self, summary_chloride):
        nb = summary_chloride["nitrogen_budget"]
        assert nb["n_allowed_per_asu"] == 2.0
        assert nb["n_assigned"] == 0
        assert "17 %" in nb["note"]
        assert "N" not in summary_chloride["element_counts"]
        rows = _rows(summary_chloride)
        carbons = [r for r in rows.values() if r["element"] == "C"]
        assert all(r["element_uncertain"] for r in carbons)
        assert all(r["element_confidence"] == "low" for r in carbons), carbons

    def test_chloride_is_recognised_as_an_unbound_ion(self, summary_chloride):
        motifs = {m["motif"] for m in summary_chloride["chem_hint"]["motifs"]}
        assert "halide_ion" in motifs, summary_chloride["chem_hint"]


# --------------------------------------------------------------------- #
# 3. metal branch regression: a Cu paddlewheel must be unchanged
# --------------------------------------------------------------------- #

class TestCuPaddlewheelRegression:

    def test_metal_branch_is_taken_and_reports_itself(self, summary_paddlewheel):
        assert summary_paddlewheel["branch"] == "metal_coordination"
        assert summary_paddlewheel["element_counts"].get("Cu", 0) >= 2, summary_paddlewheel

    def test_metal_branch_keeps_its_old_shape(self, summary_paddlewheel):
        assert "C/N ambiguity unresolved" in summary_paddlewheel["note"]
        assert "metal-coordination distance" in summary_paddlewheel["note"]
        # the metal-free extras belong to the other branch only
        for key in ("element_assignment", "nitrogen_budget", "chem_hint",
                    "tier_context", "density_measure"):
            assert key not in summary_paddlewheel, key

    def test_coordinating_oxygens_still_come_from_the_M_O_window(self, summary_paddlewheel):
        assert summary_paddlewheel["element_counts"].get("O", 0) >= 4, summary_paddlewheel

    def test_metal_override_forces_the_metal_branch(self):
        ses = _solved_session(_thiophene_like(),
                              {"C": 6, "H": 6, "O": 1, "S": 1}, z=1)
        s = _run(ses, metal_override="S")
        assert s["branch"] == "metal_coordination"


# --------------------------------------------------------------------- #
# 4. sulfur is an anchor, never a metal centre
# --------------------------------------------------------------------- #

class TestSulfurAnchor:

    def test_metal_free_branch_with_sulfur_placed_by_tier(self, summary_thiophene):
        assert summary_thiophene["branch"] == "metal_free_density_tier"
        assert summary_thiophene["element_counts"].get("S") == 1, summary_thiophene
        rows = _rows(summary_thiophene)
        s = [r for r in rows.values() if r["element"] == "S"][0]
        assert s["density_ratio"] >= 1.63                # the C/S tier line

    def test_sulfur_is_read_as_a_covalent_divalent_atom(self, summary_thiophene):
        motifs = {m["motif"] for m in summary_thiophene["chem_hint"]["motifs"]}
        assert "thioether_or_thiophene" in motifs, summary_thiophene["chem_hint"]
        assert "halide_ion" not in motifs

    def test_the_carbonyl_oxygen_survives_the_tier(self, summary_thiophene):
        assert summary_thiophene["element_counts"].get("O") == 1, summary_thiophene


# --------------------------------------------------------------------- #
# 5. the fallback path: only heights available
# --------------------------------------------------------------------- #

def test_heights_only_peak_list_says_so():
    ses = _solved_session(_benzoic_acid_dimer(), {"C": 7, "H": 6, "O": 2},
                          z=2)
    for key in ("peak_integrated_density", "peak_density_units",
                "peak_density_radius_A"):
        ses.cf_info.pop(key, None)
    s = _run(ses)
    assert s["density_measure"] == "peak HEIGHT only"
    assert "peaks.json" in s["density_note"]
    assert s["ranked_by"] == "peak height"
    # the tiers still work on heights - they are ratios either way
    assert s["element_counts"].get("O") == 4, s


def test_a_site_in_the_O_tier_beyond_the_O_allowance_says_which_fact_won():
    """When the composition's O count runs out before the density tier
    does, the site that missed out must say the COMPOSITION decided it -
    otherwise the agent reads a chemistry claim into a bookkeeping cap."""
    ses = _solved_session(_benzoic_acid_dimer(), {"C": 7, "H": 6, "O": 2},
                          z=2)
    ses.dataset.composition.elements = {"C": 8, "H": 6, "O": 1}
    s = _run(ses)
    assert s["element_counts"]["O"] == 2         # 1 per formula unit, Z=2
    squeezed = [r for r in s["element_assignment"]
                if r["element"] == "C" and "allowance" in r["reason"]]
    assert squeezed, [r["reason"] for r in s["element_assignment"][:5]]
    assert all(r["element_uncertain"] for r in squeezed)
    assert "could be the O" in squeezed[0]["reason"]


def test_a_site_below_the_H_C_line_is_not_passed_off_as_a_carbon():
    """A half-occupied site (or map noise) carries far too few electrons
    for a full-weight light atom; the tier says so instead of letting it
    ride as an ordinary C. The line is the H/C midpoint - Z 1 vs Z 6 -
    so it holds for any element, not just this fixture."""
    xs = _benzoic_acid_dimer()
    xs.scatterers()[3].occupancy = 0.15
    ses = _solved_session(xs, {"C": 7, "H": 6, "O": 2}, z=2)
    s = _run(ses)
    weak = [r for r in s["element_assignment"]
            if r.get("below_light_atom_tier")]
    assert weak, [r["density_ratio"] for r in s["element_assignment"]]
    for r in weak:
        assert r["element_confidence"] == "low"
        assert r["element_uncertain"] is True
        assert "H/C line" in r["reason"]
        assert r["density_ratio"] < 0.41
    # and a full-weight carbon is NOT flagged
    assert any(not r.get("below_light_atom_tier")
               for r in s["element_assignment"] if r["element"] == "C")


def test_unknown_composition_keeps_every_light_label_uncertain():
    ses = _solved_session(_benzoic_acid_dimer(), {"C": 7, "H": 6, "O": 2},
                          z=2)
    ses.dataset.composition = None
    s = _run(ses)
    assert s["branch"] == "metal_free_density_tier"
    assert s["composition_known"] is False
    rows = _rows(s)
    assert rows and all(r["element_uncertain"] for r in rows.values())
    assert all(r["element_confidence"] == "low" for r in rows.values())


# --------------------------------------------------------------------- #
# unit-level: the tier arithmetic is element-generic
# --------------------------------------------------------------------- #

def test_the_description_tells_the_agent_about_the_new_fields():
    d = InterpretPeaks.description
    for phrase in ("metal-free", "element_uncertain", "element_confidence",
                   "nitrogen_budget", "chem_hint", "density tier",
                   "0.7 A sphere"):
        assert phrase in d, phrase


def test_tier_lines_are_geometric_midpoints_of_Z_ratios():
    from crystalpilot.tools.peak_chemistry import (expected_ratio, tier_line)
    assert expected_ratio(6) == 1.0
    assert tier_line(6, 8) == pytest.approx(math.sqrt(8 / 6), abs=1e-6)
    assert tier_line(7, 8) == pytest.approx(math.sqrt(7 * 8 / 36), abs=1e-6)
    # symmetric in log space: the same line from either side
    assert tier_line(6, 17) == pytest.approx(tier_line(17, 6), abs=1e-9)
    # and monotone in Z, for elements nobody tested against
    assert tier_line(6, 35) > tier_line(6, 17) > tier_line(6, 8)


def test_element_split_is_by_is_metal_not_by_atomic_number():
    from crystalpilot.tools.peak_chemistry import split_elements
    metals, anchors, light = split_elements(
        ["C", "N", "O", "P", "S", "Cl", "Br", "I", "Se", "Cu", "Zn", "Si",
         "H"])
    assert metals == ["Zn", "Cu"]
    assert anchors == ["I", "Br", "Se", "Cl", "S", "P"]
    assert set(light) == {"C", "N", "O", "Si"}


def test_c_and_n_are_never_separable_but_c_and_o_are():
    from crystalpilot.tools.peak_chemistry import _competitors
    assert _competitors("C", ["C", "N", "O"]) == ["N"]
    assert _competitors("O", ["C", "N", "O"]) == ["N"]
    assert _competitors("O", ["C", "O"]) == []
    # S and Cl are 6 % apart in Z - not separable either
    assert _competitors("Cl", ["C", "S", "Cl"]) == ["S"]
