/** Client-side tiling of the scene `range` contract (round-2 R2.2, D7).
 *
 * The fixtures below are the SERVER's answers, generated by calling
 * crystalpilot.refine.scene._scene_range on a unit-cube cell with two
 * instances at the box corners (so the drawn centroid the server ranks by
 * and the box midpoint this module ranks by are the same point, and its
 * Cartesian metric is the fractional one):
 *
 *   uc = uctbx.unit_cell((1, 1, 1, 90, 90, 90))
 *   _scene_range(uc, [(0, None, lo), (0, None, hi)])
 *
 * If the two implementations ever drift, this is the test that says so.
 */
import { describe, expect, it } from "vitest";
import {
  MAX_TILES,
  centreMostTiles,
  isOriginTile,
  tileOffsetsCart,
  tilesForRange,
} from "./tiles";
import { cellVectors, type Vec3 } from "./cellMath";
import type { SceneCell } from "./wbTypes";

interface RangeFixture {
  lo: Vec3;
  hi: Vec3;
  tiles: number[][];
  n_tiles: number;
  truncated: boolean;
}

const SERVER_FIXTURES: RangeFixture[] = [
  // a grown fragment reaching back past the origin: negative translations
  {
    lo: [-1.2, 0.1, 0.0],
    hi: [1.5, 0.9, 2.0],
    tiles: [
      [-2, 0, 0], [-2, 0, 1], [-2, 0, 2], [-1, 0, 0], [-1, 0, 1], [-1, 0, 2],
      [0, 0, 0], [0, 0, 1], [0, 0, 2], [1, 0, 0], [1, 0, 1], [1, 0, 2],
    ],
    n_tiles: 12,
    truncated: false,
  },
  // a wrapped cell: the origin tile alone
  {
    lo: [0.1, 0.1, 0.1],
    hi: [0.9, 0.9, 0.9],
    tiles: [[0, 0, 0]],
    n_tiles: 1,
    truncated: false,
  },
  // 216 boxes, truncated to the 64 centre-most
  {
    lo: [-3.0, -3.0, -3.0],
    hi: [2.999, 2.999, 2.999],
    tiles: [
      [-3, -1, -1], [-3, -1, 0], [-3, 0, -1], [-2, -2, -2], [-2, -2, -1],
      [-2, -2, 0], [-2, -1, -2], [-2, -1, -1], [-2, -1, 0], [-2, -1, 1],
      [-2, 0, -2], [-2, 0, -1], [-2, 0, 0], [-2, 0, 1], [-2, 1, -1],
      [-2, 1, 0], [-1, -3, -1], [-1, -3, 0], [-1, -2, -2], [-1, -2, -1],
      [-1, -2, 0], [-1, -2, 1], [-1, -1, -3], [-1, -1, -2], [-1, -1, -1],
      [-1, -1, 0], [-1, -1, 1], [-1, 0, -3], [-1, 0, -2], [-1, 0, -1],
      [-1, 0, 0], [-1, 0, 1], [-1, 1, -2], [-1, 1, -1], [-1, 1, 0],
      [-1, 1, 1], [0, -2, -2], [0, -2, -1], [0, -2, 0], [0, -2, 1],
      [0, -1, -2], [0, -1, -1], [0, -1, 0], [0, -1, 1], [0, 0, -2],
      [0, 0, -1], [0, 0, 0], [0, 0, 1], [0, 1, -2], [0, 1, -1],
      [0, 1, 0], [0, 1, 1], [1, -2, -1], [1, -2, 0], [1, -1, -2],
      [1, -1, -1], [1, -1, 0], [1, -1, 1], [1, 0, -2], [1, 0, -1],
      [1, 0, 0], [1, 0, 1], [1, 1, -1], [1, 1, 0],
    ],
    n_tiles: 216,
    truncated: true,
  },
];

const TRICLINIC: SceneCell = {
  a: 7.1,
  b: 9.3,
  c: 11.7,
  alpha: 82.4,
  beta: 101.2,
  gamma: 96.8,
  volume: 0,
};

describe("tilesForRange agrees with the server", () => {
  for (const f of SERVER_FIXTURES) {
    it(`[${f.lo}]..[${f.hi}] -> ${f.tiles.length} of ${f.n_tiles} tiles`, () => {
      expect(tilesForRange(f.lo, f.hi, MAX_TILES)).toEqual(f.tiles);
      expect(f.truncated).toBe(f.n_tiles > MAX_TILES);
    });
  }

  it("takes the boxes [t, t+1) that MEET the range, half-open at the top", () => {
    // hi exactly on a boundary belongs to the box that starts there
    expect(tilesForRange([0, 0, 0], [1, 0, 0], MAX_TILES)).toEqual([
      [0, 0, 0],
      [1, 0, 0],
    ]);
    expect(tilesForRange([0, 0, 0], [0.999, 0, 0], MAX_TILES)).toEqual([
      [0, 0, 0],
    ]);
  });

  it("tolerates a swapped bound and rejects a non-finite one", () => {
    expect(tilesForRange([1.5, 0, 0], [-0.2, 0, 0], MAX_TILES)).toEqual(
      tilesForRange([-0.2, 0, 0], [1.5, 0, 0], MAX_TILES),
    );
    expect(tilesForRange([NaN, 0, 0], [1, 1, 1], MAX_TILES)).toEqual([
      [0, 0, 0],
    ]);
  });
});

describe("centreMostTiles", () => {
  const block = (r: number): Vec3[] => {
    const out: Vec3[] = [];
    for (let a = -r; a <= r; a += 1) {
      for (let b = -r; b <= r; b += 1) {
        for (let c = -r; c <= r; c += 1) out.push([a, b, c]);
      }
    }
    return out;
  };

  it("is symmetric about a centre that sits on a box centre", () => {
    // centre (0.5,0.5,0.5) IS the centre of tile [0,0,0], so distance
    // depends only on |t| and the kept set must close under t -> -t
    const kept = centreMostTiles(block(2), [0.5, 0.5, 0.5], 27);
    expect(kept).toEqual(block(1));
    const seven = centreMostTiles(block(2), [0.5, 0.5, 0.5], 7);
    const keys = new Set(seven.map((t) => t.join(",")));
    expect(keys.size).toBe(7);
    for (const t of seven) {
      expect(keys.has([-t[0], -t[1], -t[2]].join(","))).toBe(true);
    }
  });

  it("is deterministic and independent of the input order", () => {
    const shuffled = [...block(2)].reverse();
    const a = centreMostTiles(block(2), [0.2, -0.4, 0.9], 20);
    const b = centreMostTiles(shuffled, [0.2, -0.4, 0.9], 20);
    expect(a).toEqual(b);
    expect(centreMostTiles(a, [0.2, -0.4, 0.9], 20)).toEqual(a);
    // a tie broken by the tile triple, not by the input order
    expect(centreMostTiles(block(1), [0.5, 0.5, 0.5], 4)).toEqual([
      [-1, 0, 0],
      [0, -1, 0],
      [0, 0, -1],
      [0, 0, 0],
    ]);
  });

  it("sorts but never drops a set already within the cap", () => {
    const some: Vec3[] = [
      [1, 0, 0],
      [-1, 0, 0],
      [0, 0, 0],
    ];
    expect(centreMostTiles(some, [0.5, 0.5, 0.5], MAX_TILES)).toEqual([
      [-1, 0, 0],
      [0, 0, 0],
      [1, 0, 0],
    ]);
  });
});

describe("tileOffsetsCart", () => {
  it("moves one tile along a by the Cartesian a vector (triclinic)", () => {
    const [va, vb, vc] = cellVectors(TRICLINIC);
    expect(tileOffsetsCart(TRICLINIC, [[1, 0, 0]])[0]).toEqual(va);
    expect(tileOffsetsCart(TRICLINIC, [[0, 1, 0]])[0]).toEqual(vb);
    expect(tileOffsetsCart(TRICLINIC, [[0, 0, 1]])[0]).toEqual(vc);
  });

  it("is linear, and the origin tile moves nothing", () => {
    const [va, vb, vc] = cellVectors(TRICLINIC);
    const [zero, mixed] = tileOffsetsCart(TRICLINIC, [
      [0, 0, 0],
      [2, -1, 3],
    ]);
    expect(zero).toEqual([0, 0, 0]);
    for (let k = 0; k < 3; k += 1) {
      expect(mixed[k]).toBeCloseTo(2 * va[k] - vb[k] + 3 * vc[k], 10);
    }
  });

  it("keeps the tile order it was given", () => {
    const tiles: Vec3[] = [
      [1, 0, 0],
      [0, 0, 0],
    ];
    const offs = tileOffsetsCart(TRICLINIC, tiles);
    expect(offs[1]).toEqual([0, 0, 0]);
    expect(isOriginTile(tiles[1])).toBe(true);
    expect(isOriginTile(tiles[0])).toBe(false);
  });
});
